export const INVENTORY_LOCK_ERROR_CODES = {
  INVENTORY_LOCK_NOT_FOUND: 'INVENTORY_LOCK_NOT_FOUND',
  INVENTORY_LOCK_ALREADY_CONFIRMED: 'INVENTORY_LOCK_ALREADY_CONFIRMED',
  INVENTORY_LOCK_ALREADY_RELEASED: 'INVENTORY_LOCK_ALREADY_RELEASED',
  INVENTORY_LOCK_EXPIRED: 'INVENTORY_LOCK_EXPIRED',
  INVENTORY_LOCK_NOT_ACTIVE: 'INVENTORY_LOCK_NOT_ACTIVE',
  INVENTORY_LOCK_RELEASE_BLOCKED: 'INVENTORY_LOCK_RELEASE_BLOCKED',
  INVENTORY_LOCK_CONFIRM_BLOCKED: 'INVENTORY_LOCK_CONFIRM_BLOCKED',
  INVENTORY_LOCK_TOKEN_COLLISION: 'INVENTORY_LOCK_TOKEN_COLLISION',
  INVENTORY_LOCK_QUANTITY_INVALID: 'INVENTORY_LOCK_QUANTITY_INVALID',
  INVENTORY_LOCK_STOCK_MISMATCH: 'INVENTORY_LOCK_STOCK_MISMATCH',
  INVENTORY_LOCK_INSUFFICIENT_STOCK: 'INVENTORY_LOCK_INSUFFICIENT_STOCK',
  INVENTORY_LOCK_EXPIRY_INVALID: 'INVENTORY_LOCK_EXPIRY_INVALID',
} as const;

export type InventoryLockErrorCode =
  (typeof INVENTORY_LOCK_ERROR_CODES)[keyof typeof INVENTORY_LOCK_ERROR_CODES];
