export const CUSTOMER_ADDRESS_ERROR_CODES = {
  ADDRESS_NOT_FOUND: 'ADDRESS_NOT_FOUND',
  ADDRESS_NOT_OWNED: 'ADDRESS_NOT_OWNED',
  ADDRESS_DEFAULT_REQUIRED: 'ADDRESS_DEFAULT_REQUIRED',
  SERVICEABILITY_AREA_UNAVAILABLE: 'SERVICEABILITY_AREA_UNAVAILABLE',
  STORE_NOT_SERVICEABLE: 'STORE_NOT_SERVICEABLE',
  STORE_ALREADY_SELECTED: 'STORE_ALREADY_SELECTED',
  LOCATION_INVALID: 'LOCATION_INVALID',
  STORE_NOT_FOUND: 'STORE_NOT_FOUND',
} as const;

export type CustomerAddressErrorCode =
  (typeof CUSTOMER_ADDRESS_ERROR_CODES)[keyof typeof CUSTOMER_ADDRESS_ERROR_CODES];
