export const COLLECTION_NAMES = {
  USERS: 'users',
  USER_IDENTITIES: 'user_identities',
  AUTH_SESSIONS: 'auth_sessions',
  OTP_CHALLENGES: 'otp_challenges',
  ROLES: 'roles',
  CUSTOMERS: 'customers',
  DELIVERY_AGENTS: 'delivery_agents',
  VENDOR_USERS: 'vendor_users',
  ADMINS: 'admins',
  STORES: 'stores',
  STORE_PRODUCTS: 'store_products',
  INVENTORY_STOCKS: 'inventory_stocks',
  INVENTORY_MOVEMENTS: 'inventory_movements',
  INVENTORY_LOCKS: 'inventory_locks',
  MEDIA_FILES: 'media_files',
  CITIES: 'cities',
  SERVICE_AREAS: 'service_areas',
  PRODUCTS: 'products',
  PRODUCT_VARIANTS: 'product_variants',
  CATEGORIES: 'categories',
  BRANDS: 'brands',
  PRODUCT_UNITS: 'product_units',
  INVENTORIES: 'inventories',
  ORDERS: 'orders',
  ORDER_NOTIFICATION_PLACEHOLDERS: 'order_notification_placeholders',
  DELIVERIES: 'deliveries',
  DEVICE_TOKENS: 'device_tokens',
  PUSH_NOTIFICATION_LOGS: 'push_notification_logs',
  IN_APP_NOTIFICATIONS: 'in_app_notifications',
  AUDIT_LOGS: 'audit_logs',
  SYSTEM_CHECKS: 'system_checks',
  TENANT_ACCESS_TESTS: 'tenant_access_tests',
  CUSTOMER_ADDRESSES: 'customer_addresses',
  CUSTOMER_STORE_SELECTIONS: 'customer_store_selections',
  CARTS: 'carts',
  CHECKOUT_SESSIONS: 'checkout_sessions',
  PAYMENTS: 'payments',
} as const;

export type CollectionName = (typeof COLLECTION_NAMES)[keyof typeof COLLECTION_NAMES];
