import { ORDER_AUDIT_EVENTS } from './order-audit-events.constant';

export const ORDER_NOTIFICATION_EVENTS = {
  CANCELLED: ORDER_AUDIT_EVENTS.CANCELLED,
  ITEM_MISSING: ORDER_AUDIT_EVENTS.ITEM_MISSING,
  PACKING_COMPLETED: ORDER_AUDIT_EVENTS.PACKING_COMPLETED,
  PACKING_STARTED: ORDER_AUDIT_EVENTS.PACKING_STARTED,
  PICKING_COMPLETED: ORDER_AUDIT_EVENTS.PICKING_COMPLETED,
  PICKING_STARTED: ORDER_AUDIT_EVENTS.PICKING_STARTED,
  READY_FOR_PICKUP: ORDER_AUDIT_EVENTS.READY_FOR_PICKUP,
  STORE_ACCEPTED: ORDER_AUDIT_EVENTS.STORE_ACCEPTED,
  STORE_REJECTED: ORDER_AUDIT_EVENTS.STORE_REJECTED,
  ASSIGNED: 'assigned',
  PICKED_UP: 'picked_up',
  DELIVERED: 'delivered',
} as const;

export const ORDER_NOTIFICATION_EVENT_VALUES = Object.values(ORDER_NOTIFICATION_EVENTS);

export type OrderNotificationEvent = (typeof ORDER_NOTIFICATION_EVENT_VALUES)[number];

export const ORDER_NOTIFICATION_RECIPIENT_TYPES = {
  ADMIN: 'admin',
  CUSTOMER: 'customer',
  VENDOR: 'vendor',
  AGENT: 'agent',
} as const;

export const ORDER_NOTIFICATION_RECIPIENT_TYPE_VALUES = Object.values(
  ORDER_NOTIFICATION_RECIPIENT_TYPES,
);

export type OrderNotificationRecipientType =
  (typeof ORDER_NOTIFICATION_RECIPIENT_TYPE_VALUES)[number];

export const ORDER_NOTIFICATION_PLACEHOLDER_STATUS = {
  QUEUED_PLACEHOLDER: 'queued_placeholder',
  SKIPPED_PLACEHOLDER: 'skipped_placeholder',
} as const;

export const ORDER_NOTIFICATION_PLACEHOLDER_STATUS_VALUES = Object.values(
  ORDER_NOTIFICATION_PLACEHOLDER_STATUS,
);

export type OrderNotificationPlaceholderStatus =
  (typeof ORDER_NOTIFICATION_PLACEHOLDER_STATUS_VALUES)[number];
