export const ORDER_FINANCE_STATUS = {
  UNPAID: 'unpaid',
  PAID: 'paid',
  REFUND_DUE: 'refund_due',
  REFUND_PROCESSING: 'refund_processing',
  REFUND_CLOSED: 'refund_closed',
  SETTLEMENT_PENDING: 'settlement_pending',
  SETTLEMENT_READY: 'settlement_ready',
  CLOSED: 'closed',
} as const;

export const ORDER_FINANCE_STATUS_VALUES = [
  ORDER_FINANCE_STATUS.UNPAID,
  ORDER_FINANCE_STATUS.PAID,
  ORDER_FINANCE_STATUS.REFUND_DUE,
  ORDER_FINANCE_STATUS.REFUND_PROCESSING,
  ORDER_FINANCE_STATUS.REFUND_CLOSED,
  ORDER_FINANCE_STATUS.SETTLEMENT_PENDING,
  ORDER_FINANCE_STATUS.SETTLEMENT_READY,
  ORDER_FINANCE_STATUS.CLOSED,
] as const;

export type OrderFinanceStatus = (typeof ORDER_FINANCE_STATUS_VALUES)[number];
