export const ORDER_ERROR_CODES = {
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  ORDER_NOT_OWNED: 'ORDER_NOT_OWNED',
  ORDER_ALREADY_EXISTS: 'ORDER_ALREADY_EXISTS',
  ORDER_CREATION_FAILED: 'ORDER_CREATION_FAILED',
  ORDER_SCOPE_REQUIRED: 'ORDER_SCOPE_REQUIRED',
  ORDER_ACCESS_FORBIDDEN: 'ORDER_ACCESS_FORBIDDEN',
  ORDER_ACCEPTANCE_NOT_ALLOWED: 'ORDER_ACCEPTANCE_NOT_ALLOWED',
  ORDER_REJECTION_REASON_REQUIRED: 'ORDER_REJECTION_REASON_REQUIRED',
  ORDER_PICKING_NOT_ALLOWED: 'ORDER_PICKING_NOT_ALLOWED',
  ORDER_PACKING_NOT_ALLOWED: 'ORDER_PACKING_NOT_ALLOWED',
  ORDER_STATUS_UPDATE_NOT_ALLOWED: 'ORDER_STATUS_UPDATE_NOT_ALLOWED',
  ORDER_CANCELLATION_NOT_ALLOWED: 'ORDER_CANCELLATION_NOT_ALLOWED',
  ORDER_CANCELLATION_REASON_REQUIRED: 'ORDER_CANCELLATION_REASON_REQUIRED',
  ORDER_ITEM_OPERATION_INVALID: 'ORDER_ITEM_OPERATION_INVALID',
} as const;

export type OrderErrorCode = (typeof ORDER_ERROR_CODES)[keyof typeof ORDER_ERROR_CODES];
