export const PRODUCT_ERROR_CODES = {
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  PRODUCT_SLUG_ALREADY_EXISTS: 'PRODUCT_SLUG_ALREADY_EXISTS',
  PRODUCT_NOT_APPROVED: 'PRODUCT_NOT_APPROVED',
  PRODUCT_NOT_VISIBLE: 'PRODUCT_NOT_VISIBLE',
  INVALID_PRODUCT_STATUS: 'INVALID_PRODUCT_STATUS',
  INVALID_PRODUCT_TYPE: 'INVALID_PRODUCT_TYPE',
  INVALID_FOOD_TYPE: 'INVALID_FOOD_TYPE',
  INVALID_PRODUCT_APPROVAL_STATUS: 'INVALID_PRODUCT_APPROVAL_STATUS',
  INVALID_PRODUCT_CATEGORY: 'INVALID_PRODUCT_CATEGORY',
  INVALID_PRODUCT_SUBCATEGORY: 'INVALID_PRODUCT_SUBCATEGORY',
  INVALID_PRODUCT_BRAND: 'INVALID_PRODUCT_BRAND',
  PRODUCT_HAS_ACTIVE_VARIANTS: 'PRODUCT_HAS_ACTIVE_VARIANTS',
  PRODUCT_HAS_ACTIVE_STORE_PRODUCTS: 'PRODUCT_HAS_ACTIVE_STORE_PRODUCTS',
  REJECTION_REASON_REQUIRED: 'REJECTION_REASON_REQUIRED',
} as const;

export type ProductErrorCode =
  (typeof PRODUCT_ERROR_CODES)[keyof typeof PRODUCT_ERROR_CODES];
