export const PRODUCT_APPROVAL_STATUS = {
  DRAFT: 'draft',
  PENDING_REVIEW: 'pending_review',
  APPROVED: 'approved',
  REJECTED: 'rejected',
  ARCHIVED: 'archived',
} as const;

export type ProductApprovalStatus =
  (typeof PRODUCT_APPROVAL_STATUS)[keyof typeof PRODUCT_APPROVAL_STATUS];

export const PRODUCT_APPROVAL_STATUS_VALUES = [
  PRODUCT_APPROVAL_STATUS.DRAFT,
  PRODUCT_APPROVAL_STATUS.PENDING_REVIEW,
  PRODUCT_APPROVAL_STATUS.APPROVED,
  PRODUCT_APPROVAL_STATUS.REJECTED,
  PRODUCT_APPROVAL_STATUS.ARCHIVED,
] as const;
