export const STORE_ERROR_CODES = {
  STORE_NOT_FOUND: 'STORE_NOT_FOUND',
  STORE_SLUG_ALREADY_EXISTS: 'STORE_SLUG_ALREADY_EXISTS',
  STORE_CODE_ALREADY_EXISTS: 'STORE_CODE_ALREADY_EXISTS',
  STORE_HAS_ACTIVE_ORDERS: 'STORE_HAS_ACTIVE_ORDERS',
  INVALID_STORE_STATUS: 'INVALID_STORE_STATUS',
  INVALID_STORE_TYPE: 'INVALID_STORE_TYPE',
  INVALID_FULFILLMENT_TYPE: 'INVALID_FULFILLMENT_TYPE',
  INVALID_STORE_CITY: 'INVALID_STORE_CITY',
  INVALID_STORE_SERVICE_AREA: 'INVALID_STORE_SERVICE_AREA',
  TEMPORARY_CLOSURE_REASON_REQUIRED: 'TEMPORARY_CLOSURE_REASON_REQUIRED',
  STORE_CODE_IMMUTABLE: 'STORE_CODE_IMMUTABLE',
} as const;

export type StoreErrorCode = (typeof STORE_ERROR_CODES)[keyof typeof STORE_ERROR_CODES];
