export const LEDGER_SYSTEM_ACCOUNT_CODE = {
  PAYMENT_GATEWAY_RECEIVABLE: 'PAYMENT_GATEWAY_RECEIVABLE',
  VENDOR_PAYABLE: 'VENDOR_PAYABLE',
  DELIVERY_PARTNER_PAYABLE: 'DELIVERY_PARTNER_PAYABLE',
  PLATFORM_FEE_REVENUE: 'PLATFORM_FEE_REVENUE',
  DELIVERY_FEE_REVENUE: 'DELIVERY_FEE_REVENUE',
  COMMISSION_REVENUE: 'COMMISSION_REVENUE',
  TAX_PAYABLE: 'TAX_PAYABLE',
  REFUND_PAYABLE: 'REFUND_PAYABLE',
  DISCOUNT_EXPENSE: 'DISCOUNT_EXPENSE',
  MANUAL_ADJUSTMENT: 'MANUAL_ADJUSTMENT',
} as const;

export const LEDGER_SYSTEM_ACCOUNT_CODE_VALUES = Object.values(LEDGER_SYSTEM_ACCOUNT_CODE);

export type LedgerSystemAccountCode =
  (typeof LEDGER_SYSTEM_ACCOUNT_CODE)[keyof typeof LEDGER_SYSTEM_ACCOUNT_CODE];
