export const LEDGER_ERROR_CODES = {
  LEDGER_ACCOUNT_NOT_FOUND: 'LEDGER_ACCOUNT_NOT_FOUND',
  LEDGER_ACCOUNT_CODE_ALREADY_EXISTS: 'LEDGER_ACCOUNT_CODE_ALREADY_EXISTS',
  LEDGER_ACCOUNT_ARCHIVED: 'LEDGER_ACCOUNT_ARCHIVED',
  LEDGER_ACCOUNT_POSTING_NOT_ALLOWED: 'LEDGER_ACCOUNT_POSTING_NOT_ALLOWED',
  LEDGER_ACCOUNT_HAS_POSTED_LINES: 'LEDGER_ACCOUNT_HAS_POSTED_LINES',
  LEDGER_SYSTEM_ACCOUNT_IMMUTABLE: 'LEDGER_SYSTEM_ACCOUNT_IMMUTABLE',
  LEDGER_JOURNAL_NOT_FOUND: 'LEDGER_JOURNAL_NOT_FOUND',
  LEDGER_JOURNAL_NOT_BALANCED: 'LEDGER_JOURNAL_NOT_BALANCED',
  LEDGER_JOURNAL_ALREADY_POSTED: 'LEDGER_JOURNAL_ALREADY_POSTED',
  LEDGER_JOURNAL_CANNOT_REVERSE: 'LEDGER_JOURNAL_CANNOT_REVERSE',
  LEDGER_JOURNAL_ALREADY_REVERSED: 'LEDGER_JOURNAL_ALREADY_REVERSED',
  LEDGER_IDEMPOTENCY_KEY_ALREADY_USED: 'LEDGER_IDEMPOTENCY_KEY_ALREADY_USED',
  LEDGER_LINE_INVALID: 'LEDGER_LINE_INVALID',
  LEDGER_PARENT_ACCOUNT_INVALID: 'LEDGER_PARENT_ACCOUNT_INVALID',
  LEDGER_POSTING_FAILED: 'LEDGER_POSTING_FAILED',
} as const;

export type LedgerErrorCode =
  (typeof LEDGER_ERROR_CODES)[keyof typeof LEDGER_ERROR_CODES];
