export const CART_ERROR_CODES = {
  CART_NOT_FOUND: 'CART_NOT_FOUND',
  CART_ITEM_NOT_FOUND: 'CART_ITEM_NOT_FOUND',
  CART_EMPTY: 'CART_EMPTY',
  CART_PRODUCT_UNAVAILABLE: 'CART_PRODUCT_UNAVAILABLE',
  CART_INSUFFICIENT_STOCK: 'CART_INSUFFICIENT_STOCK',
  CART_MAX_QUANTITY_EXCEEDED: 'CART_MAX_QUANTITY_EXCEEDED',
  CART_STORE_MISMATCH: 'CART_STORE_MISMATCH',
  CART_PRICE_CHANGED: 'CART_PRICE_CHANGED',
  STORE_NOT_FOUND: 'STORE_NOT_FOUND',
} as const;

export type CartErrorCode = (typeof CART_ERROR_CODES)[keyof typeof CART_ERROR_CODES];
