export const SERVICE_AREA_ERROR_CODES = {
  SERVICE_AREA_NOT_FOUND: 'SERVICE_AREA_NOT_FOUND',
  SERVICE_AREA_SLUG_ALREADY_EXISTS: 'SERVICE_AREA_SLUG_ALREADY_EXISTS',
  SERVICE_AREA_HAS_ACTIVE_STORES: 'SERVICE_AREA_HAS_ACTIVE_STORES',
  INVALID_SERVICE_AREA_STATUS: 'INVALID_SERVICE_AREA_STATUS',
  INVALID_SERVICE_AREA_CITY: 'INVALID_SERVICE_AREA_CITY',
  SERVICE_AREA_NOT_SERVICEABLE: 'SERVICE_AREA_NOT_SERVICEABLE',
} as const;

export type ServiceAreaErrorCode =
  (typeof SERVICE_AREA_ERROR_CODES)[keyof typeof SERVICE_AREA_ERROR_CODES];
