export const CITY_ERROR_CODES = {
  CITY_NOT_FOUND: 'CITY_NOT_FOUND',
  CITY_SLUG_ALREADY_EXISTS: 'CITY_SLUG_ALREADY_EXISTS',
  CITY_HAS_ACTIVE_SERVICE_AREAS: 'CITY_HAS_ACTIVE_SERVICE_AREAS',
  CITY_HAS_ACTIVE_STORES: 'CITY_HAS_ACTIVE_STORES',
  INVALID_CITY_STATUS: 'INVALID_CITY_STATUS',
  CITY_NOT_SERVICEABLE: 'CITY_NOT_SERVICEABLE',
} as const;

export type CityErrorCode = (typeof CITY_ERROR_CODES)[keyof typeof CITY_ERROR_CODES];
