export const CATEGORY_ERROR_CODES = {
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  CATEGORY_SLUG_ALREADY_EXISTS: 'CATEGORY_SLUG_ALREADY_EXISTS',
  CATEGORY_HAS_CHILDREN: 'CATEGORY_HAS_CHILDREN',
  CATEGORY_HAS_ACTIVE_PRODUCTS: 'CATEGORY_HAS_ACTIVE_PRODUCTS',
  INVALID_PARENT_CATEGORY: 'INVALID_PARENT_CATEGORY',
  CATEGORY_LEVEL_LIMIT_EXCEEDED: 'CATEGORY_LEVEL_LIMIT_EXCEEDED',
} as const;

export type CategoryErrorCode =
  (typeof CATEGORY_ERROR_CODES)[keyof typeof CATEGORY_ERROR_CODES];
