export const CHECKOUT_ERROR_CODES = {
  CHECKOUT_SESSION_NOT_FOUND: 'CHECKOUT_SESSION_NOT_FOUND',
  CHECKOUT_SESSION_EXPIRED: 'CHECKOUT_SESSION_EXPIRED',
  CHECKOUT_CART_EMPTY: 'CHECKOUT_CART_EMPTY',
  CHECKOUT_STOCK_UNAVAILABLE: 'CHECKOUT_STOCK_UNAVAILABLE',
  CHECKOUT_PRICE_CHANGED: 'CHECKOUT_PRICE_CHANGED',
  CHECKOUT_ADDRESS_UNSERVICEABLE: 'CHECKOUT_ADDRESS_UNSERVICEABLE',
  CHECKOUT_STORE_CLOSED: 'CHECKOUT_STORE_CLOSED',
} as const;

export type CheckoutErrorCode =
  (typeof CHECKOUT_ERROR_CODES)[keyof typeof CHECKOUT_ERROR_CODES];
