export const PRODUCT_UNIT_ERROR_CODES = {
  PRODUCT_UNIT_NOT_FOUND: 'PRODUCT_UNIT_NOT_FOUND',
  PRODUCT_UNIT_CODE_ALREADY_EXISTS: 'PRODUCT_UNIT_CODE_ALREADY_EXISTS',
  PRODUCT_UNIT_IN_USE: 'PRODUCT_UNIT_IN_USE',
  INVALID_PRODUCT_UNIT_STATUS: 'INVALID_PRODUCT_UNIT_STATUS',
  INVALID_BASE_UNIT: 'INVALID_BASE_UNIT',
  INVALID_CONVERSION_FACTOR: 'INVALID_CONVERSION_FACTOR',
} as const;

export type ProductUnitErrorCode =
  (typeof PRODUCT_UNIT_ERROR_CODES)[keyof typeof PRODUCT_UNIT_ERROR_CODES];
