export const ADMIN_ACTION_TYPE = {
  FORCE_ASSIGNMENT: 'FORCE_ASSIGNMENT',
  FORCE_UNASSIGN: 'FORCE_UNASSIGN',
  FORCE_ORDER_CANCEL: 'FORCE_ORDER_CANCEL',
  FORCE_STORE_CLOSE: 'FORCE_STORE_CLOSE',
  FORCE_AGENT_OFFLINE: 'FORCE_AGENT_OFFLINE',
  MARK_SLA_ESCALATED: 'MARK_SLA_ESCALATED',
  OVERRIDE_DELIVERY_ZONE: 'OVERRIDE_DELIVERY_ZONE',
  ADMIN_USER_CREATED: 'ADMIN_USER_CREATED',
  ADMIN_USER_UPDATED: 'ADMIN_USER_UPDATED',
  ADMIN_USER_STATUS_CHANGED: 'ADMIN_USER_STATUS_CHANGED',
  ADMIN_USER_ROLE_CHANGED: 'ADMIN_USER_ROLE_CHANGED',
  ADMIN_USER_PERMISSIONS_CHANGED: 'ADMIN_USER_PERMISSIONS_CHANGED',
  CUSTOMER_STATUS_CHANGED: 'CUSTOMER_STATUS_CHANGED',
  CUSTOMER_NOTE_UPDATED: 'CUSTOMER_NOTE_UPDATED',
} as const;

export const ADMIN_ACTION_TYPES = Object.values(ADMIN_ACTION_TYPE);
