"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const strict_1 = __importDefault(require("node:assert/strict"));
const node_fs_1 = require("node:fs");
const node_path_1 = require("node:path");
const node_test_1 = require("node:test");
const readSource = (path) => (0, node_fs_1.readFileSync)((0, node_path_1.resolve)(process.cwd(), path), 'utf8');
(0, node_test_1.test)('catalog oversight API client consumes existing admin catalog endpoints only', () => {
    const source = readSource('src/modules/catalog/api/product.api.ts');
    const categorySource = readSource('src/modules/catalog/api/category.api.ts');
    const brandSource = readSource('src/modules/catalog/api/brand.api.ts');
    const unitSource = readSource('src/modules/catalog/api/product-unit.api.ts');
    strict_1.default.match(categorySource, /const BASE = '\/api\/v1\/admin\/catalog\/categories'/);
    strict_1.default.match(brandSource, /const BASE = '\/api\/v1\/admin\/catalog\/brands'/);
    strict_1.default.match(unitSource, /const BASE = '\/api\/v1\/admin\/catalog\/units'/);
    strict_1.default.match(source, /const BASE = '\/api\/v1\/admin\/catalog\/products'/);
    strict_1.default.match(source, /`\$\{BASE\}\/\$\{productId\}\/approval-status`/);
    strict_1.default.match(source, /`\$\{BASE\}\/\$\{productId\}\/variants`/);
    strict_1.default.match(source, /`\$\{BASE\}\/\$\{productId\}\/variants\/\$\{variantId\}`/);
    strict_1.default.doesNotMatch(source, /\/vendor\/catalog|\/customer\/catalog|\/stores|\/inventory|\/promotions|\/exports/);
});
(0, node_test_1.test)('catalog oversight variant client exposes typed read and mutation helpers', () => {
    const source = readSource('src/modules/catalog/api/product.api.ts');
    const typeSource = readSource('src/modules/catalog/types/product-variant.types.ts');
    const hookSource = readSource('src/modules/catalog/hooks/useProductVariantMutations.ts');
    strict_1.default.match(typeSource, /export type ProductVariantResponse = \{/);
    strict_1.default.match(typeSource, /export type ProductVariantFormValues = \{/);
    strict_1.default.match(typeSource, /export type ProductVariantListQuery = \{/);
    strict_1.default.match(source, /getAdminProductVariants/);
    strict_1.default.match(source, /getAdminProductVariantsPage/);
    strict_1.default.match(source, /createAdminProductVariant/);
    strict_1.default.match(source, /updateAdminProductVariant/);
    strict_1.default.match(source, /deleteAdminProductVariant/);
    strict_1.default.match(source, /unwrapPaginated/);
    strict_1.default.match(hookSource, /useProductVariantMutations/);
    strict_1.default.match(hookSource, /\['admin-product-variants', productId\]/);
});
(0, node_test_1.test)('catalog route gates remain permission scoped', () => {
    const routeSource = readSource('src/routes/catalog.routes.tsx');
    strict_1.default.match(routeSource, /permission="catalog:read"/);
    strict_1.default.match(routeSource, /permission="catalog:create"/);
    strict_1.default.match(routeSource, /permission="catalog:update"/);
    strict_1.default.match(routeSource, /\/catalog\/products\/:productId\/variants/);
    strict_1.default.doesNotMatch(routeSource, /stores:|delivery:|customer:|settings:manage/);
});
(0, node_test_1.test)('category oversight exposes read-only detail and gates mutation actions', () => {
    const routeSource = readSource('src/routes/catalog.routes.tsx');
    const listSource = readSource('src/modules/catalog/pages/categories/CategoryListPage.tsx');
    const detailSource = readSource('src/modules/catalog/pages/categories/CategoryDetailPage.tsx');
    strict_1.default.match(routeSource, /path: '\/catalog\/categories\/:categoryId'/);
    strict_1.default.match(routeSource, /<CategoryDetailPage \/>/);
    strict_1.default.match(routeSource, /permission="catalog:read"/);
    strict_1.default.match(listSource, /to=\{`\/catalog\/categories\/\$\{row\.id\}`\}/);
    strict_1.default.match(listSource, /permission="catalog:update"/);
    strict_1.default.match(listSource, /permission="catalog:delete"/);
    strict_1.default.match(detailSource, /useCategoryDetail\(categoryId\)/);
    strict_1.default.match(detailSource, /permission="catalog:update"/);
    strict_1.default.match(detailSource, /CatalogStatusBadge/);
    strict_1.default.doesNotMatch(detailSource, /deleteMutation|useCategoryMutations/);
});
(0, node_test_1.test)('category mutation surfaces use existing category endpoints and guards', () => {
    const apiSource = readSource('src/modules/catalog/api/category.api.ts');
    const createSource = readSource('src/modules/catalog/pages/categories/CategoryCreatePage.tsx');
    const editSource = readSource('src/modules/catalog/pages/categories/CategoryEditPage.tsx');
    const hookSource = readSource('src/modules/catalog/hooks/useCategoryMutations.ts');
    const formSource = readSource('src/modules/catalog/forms/CategoryForm.tsx');
    strict_1.default.match(apiSource, /createAdminCategory/);
    strict_1.default.match(apiSource, /updateAdminCategory/);
    strict_1.default.match(apiSource, /deleteAdminCategory/);
    strict_1.default.match(createSource, /createMutation\.mutateAsync\(values\)/);
    strict_1.default.match(editSource, /updateMutation\.mutateAsync\(\{ categoryId, payload: values \}\)/);
    strict_1.default.match(editSource, /excludeParentId=\{categoryId\}/);
    strict_1.default.match(hookSource, /invalidateQueries\(\{ queryKey: \['admin-categories'\] \}\)/);
    strict_1.default.match(hookSource, /invalidateQueries\(\{ queryKey: \['admin-category'\] \}\)/);
    strict_1.default.match(formSource, /categoryFormSchema/);
    strict_1.default.match(formSource, /CategorySelect/);
    strict_1.default.doesNotMatch(apiSource, /hardDelete|\/stores|\/inventory|\/vendor|\/customer/);
});
(0, node_test_1.test)('brand and unit oversight expose detail routes and gate mutations', () => {
    const routeSource = readSource('src/routes/catalog.routes.tsx');
    const brandListSource = readSource('src/modules/catalog/pages/brands/BrandListPage.tsx');
    const brandDetailSource = readSource('src/modules/catalog/pages/brands/BrandDetailPage.tsx');
    const unitListSource = readSource('src/modules/catalog/pages/units/ProductUnitListPage.tsx');
    const unitDetailSource = readSource('src/modules/catalog/pages/units/ProductUnitDetailPage.tsx');
    strict_1.default.match(routeSource, /path: '\/catalog\/brands\/:brandId'/);
    strict_1.default.match(routeSource, /path: '\/catalog\/units\/:unitId'/);
    strict_1.default.match(routeSource, /<BrandDetailPage \/>/);
    strict_1.default.match(routeSource, /<ProductUnitDetailPage \/>/);
    strict_1.default.match(brandListSource, /to=\{`\/catalog\/brands\/\$\{row\.id\}`\}/);
    strict_1.default.match(unitListSource, /to=\{`\/catalog\/units\/\$\{row\.id\}`\}/);
    strict_1.default.match(brandListSource, /permission="catalog:update"/);
    strict_1.default.match(unitListSource, /permission="catalog:update"/);
    strict_1.default.match(brandDetailSource, /useBrandDetail\(brandId\)/);
    strict_1.default.match(unitDetailSource, /useProductUnitDetail\(unitId\)/);
    strict_1.default.doesNotMatch(brandDetailSource, /useBrandMutations|deleteMutation/);
    strict_1.default.doesNotMatch(unitDetailSource, /useProductUnitMutations|deleteMutation/);
});
(0, node_test_1.test)('product oversight read views expose filters detail and permission-gated actions', () => {
    const routeSource = readSource('src/routes/catalog.routes.tsx');
    const listSource = readSource('src/modules/catalog/pages/products/ProductListPage.tsx');
    const detailSource = readSource('src/modules/catalog/pages/products/ProductDetailPage.tsx');
    strict_1.default.match(routeSource, /path: '\/catalog\/products'/);
    strict_1.default.match(routeSource, /path: '\/catalog\/products\/:productId'/);
    strict_1.default.match(routeSource, /permission="catalog:read"/);
    strict_1.default.match(listSource, /useProducts\(\)/);
    strict_1.default.match(listSource, /Approval status/);
    strict_1.default.match(listSource, /Food type/);
    strict_1.default.match(listSource, /Product type/);
    strict_1.default.match(listSource, /Visibility/);
    strict_1.default.match(listSource, /Featured/);
    strict_1.default.match(listSource, /permission="catalog:update"/);
    strict_1.default.match(listSource, /permission="catalog:approve"/);
    strict_1.default.match(listSource, /permission="catalog:delete"/);
    strict_1.default.match(detailSource, /useProductDetail\(productId\)/);
    strict_1.default.match(detailSource, /to=\{`\/catalog\/products\/\$\{record\.id\}\/variants`\}/);
    strict_1.default.match(detailSource, /PRODUCT_APPROVAL_STATUS_LABELS/);
    strict_1.default.doesNotMatch(detailSource, /storeProduct|inventory|vendor|customer/i);
});
(0, node_test_1.test)('product mutation surfaces use master catalog APIs only', () => {
    const apiSource = readSource('src/modules/catalog/api/product.api.ts');
    const createSource = readSource('src/modules/catalog/pages/products/ProductCreatePage.tsx');
    const editSource = readSource('src/modules/catalog/pages/products/ProductEditPage.tsx');
    const hookSource = readSource('src/modules/catalog/hooks/useProductMutations.ts');
    const formSource = readSource('src/modules/catalog/forms/ProductForm.tsx');
    strict_1.default.match(apiSource, /createAdminProduct/);
    strict_1.default.match(apiSource, /updateAdminProduct/);
    strict_1.default.match(apiSource, /deleteAdminProduct/);
    strict_1.default.match(createSource, /createMutation\.mutateAsync\(values\)/);
    strict_1.default.match(editSource, /updateMutation\.mutateAsync\(\{ payload: values, productId \}\)/);
    strict_1.default.match(formSource, /ProductForm/);
    strict_1.default.match(formSource, /CategorySelect/);
    strict_1.default.match(formSource, /BrandSelect/);
    strict_1.default.match(hookSource, /invalidateQueries\(\{ queryKey: \['admin-products'\] \}\)/);
    strict_1.default.match(hookSource, /invalidateQueries\(\{ queryKey: \['admin-product'\] \}\)/);
    strict_1.default.doesNotMatch(apiSource, /\/store-products|\/inventory|\/vendor|\/customer|pricing/);
    strict_1.default.doesNotMatch(formSource, /stock|inventory|storePrice|sellingPrice/);
});
(0, node_test_1.test)('product approval workflow uses approval permission and endpoint only', () => {
    const apiSource = readSource('src/modules/catalog/api/product.api.ts');
    const listSource = readSource('src/modules/catalog/pages/products/ProductListPage.tsx');
    const detailSource = readSource('src/modules/catalog/pages/products/ProductDetailPage.tsx');
    const dialogSource = readSource('src/modules/catalog/components/ProductApprovalDialog.tsx');
    const schemaSource = readSource('src/modules/catalog/forms/product-approval.schema.ts');
    strict_1.default.match(apiSource, /updateAdminProductApprovalStatus/);
    strict_1.default.match(apiSource, /`\$\{BASE\}\/\$\{productId\}\/approval-status`/);
    strict_1.default.match(listSource, /permission="catalog:approve"/);
    strict_1.default.match(detailSource, /permission="catalog:approve"/);
    strict_1.default.match(dialogSource, /ProductApprovalDialog/);
    strict_1.default.match(schemaSource, /productApprovalSchema/);
    strict_1.default.match(schemaSource, /rejectionReason/);
    strict_1.default.doesNotMatch(apiSource, /\/status`|\/stores|\/inventory|\/vendor|\/customer/);
});
(0, node_test_1.test)('variant oversight supports nested product variant CRUD only', () => {
    const routeSource = readSource('src/routes/catalog.routes.tsx');
    const pageSource = readSource('src/modules/catalog/pages/variants/VariantListPage.tsx');
    const formSource = readSource('src/modules/catalog/forms/ProductVariantForm.tsx');
    const schemaSource = readSource('src/modules/catalog/forms/product-variant-form.schema.ts');
    const apiSource = readSource('src/modules/catalog/api/product.api.ts');
    strict_1.default.match(routeSource, /path: '\/catalog\/products\/:productId\/variants'/);
    strict_1.default.match(pageSource, /getAdminProductVariants\(productId, \{ limit: 500 \}\)/);
    strict_1.default.match(pageSource, /useProductVariantMutations\(productId \?\? ''\)/);
    strict_1.default.match(pageSource, /permission="catalog:create"/);
    strict_1.default.match(pageSource, /permission="catalog:update"/);
    strict_1.default.match(pageSource, /permission="catalog:delete"/);
    strict_1.default.match(formSource, /ProductVariantForm/);
    strict_1.default.match(schemaSource, /productVariantFormSchema/);
    strict_1.default.match(apiSource, /createAdminProductVariant/);
    strict_1.default.match(apiSource, /updateAdminProductVariant/);
    strict_1.default.match(apiSource, /deleteAdminProductVariant/);
    strict_1.default.doesNotMatch(pageSource, /storeProduct|inventory|sellingPrice|vendor|customer/i);
});
