export const IN_APP_NOTIFICATION_ERROR_CODES = {
  NOTIFICATION_NOT_FOUND: 'NOTIFICATION_NOT_FOUND',
  NOTIFICATION_SCOPE_DENIED: 'NOTIFICATION_SCOPE_DENIED',
  INVALID_NOTIFICATION_TYPE: 'INVALID_NOTIFICATION_TYPE',
  INVALID_NOTIFICATION_PRIORITY: 'INVALID_NOTIFICATION_PRIORITY',
} as const;

export type InAppNotificationErrorCode =
  (typeof IN_APP_NOTIFICATION_ERROR_CODES)[keyof typeof IN_APP_NOTIFICATION_ERROR_CODES];
