"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.canShowStoreCancellationAction = exports.canShowReadyForPickupAction = exports.canShowCompletePackingAction = exports.canShowStartPackingAction = exports.canShowCompletePickingAction = exports.canShowItemPickingActions = exports.canShowStartPickingAction = exports.canUpdateVendorOrderHistory = exports.canReadVendorOrderHistory = exports.canUpdateVendorPickingPacking = exports.canReadVendorActiveOrders = exports.canUpdateVendorOrders = exports.canReadVendorOrders = void 0;
const permission_visibility_util_1 = require("../../../access-control/permission-visibility.util");
const vendor_orders_workflow_util_1 = require("./vendor-orders-workflow.util");
const canReadVendorOrders = (permissions) => (0, permission_visibility_util_1.shouldRenderPermissionGatedContent)(permissions, 'orders:read');
exports.canReadVendorOrders = canReadVendorOrders;
const canUpdateVendorOrders = (permissions) => (0, permission_visibility_util_1.shouldRenderPermissionGatedContent)(permissions, 'orders:update');
exports.canUpdateVendorOrders = canUpdateVendorOrders;
exports.canReadVendorActiveOrders = exports.canReadVendorOrders;
exports.canUpdateVendorPickingPacking = exports.canUpdateVendorOrders;
exports.canReadVendorOrderHistory = exports.canReadVendorOrders;
exports.canUpdateVendorOrderHistory = exports.canUpdateVendorOrders;
const canShowStartPickingAction = (permissions, order) => (0, exports.canUpdateVendorPickingPacking)(permissions) && (0, vendor_orders_workflow_util_1.canStartVendorOrderPicking)(order);
exports.canShowStartPickingAction = canShowStartPickingAction;
const canShowItemPickingActions = (permissions, order) => (0, exports.canUpdateVendorPickingPacking)(permissions) && (0, vendor_orders_workflow_util_1.canUpdateVendorOrderItemPicking)(order);
exports.canShowItemPickingActions = canShowItemPickingActions;
const canShowCompletePickingAction = (permissions, order) => (0, exports.canUpdateVendorPickingPacking)(permissions) && (0, vendor_orders_workflow_util_1.canCompleteVendorOrderPicking)(order);
exports.canShowCompletePickingAction = canShowCompletePickingAction;
const canShowStartPackingAction = (permissions, order) => (0, exports.canUpdateVendorPickingPacking)(permissions) && (0, vendor_orders_workflow_util_1.canStartVendorOrderPacking)(order);
exports.canShowStartPackingAction = canShowStartPackingAction;
const canShowCompletePackingAction = (permissions, order) => (0, exports.canUpdateVendorPickingPacking)(permissions) && (0, vendor_orders_workflow_util_1.canCompleteVendorOrderPacking)(order);
exports.canShowCompletePackingAction = canShowCompletePackingAction;
const canShowReadyForPickupAction = (permissions, order) => (0, exports.canUpdateVendorPickingPacking)(permissions) && (0, vendor_orders_workflow_util_1.canMarkVendorOrderReadyForPickup)(order);
exports.canShowReadyForPickupAction = canShowReadyForPickupAction;
const canShowStoreCancellationAction = (permissions, order) => (0, exports.canUpdateVendorOrderHistory)(permissions) && (0, vendor_orders_workflow_util_1.canCancelVendorStoreOrder)(order);
exports.canShowStoreCancellationAction = canShowStoreCancellationAction;
