"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const strict_1 = __importDefault(require("node:assert/strict"));
const node_fs_1 = require("node:fs");
const node_path_1 = require("node:path");
const node_test_1 = require("node:test");
const readSource = (path) => (0, node_fs_1.readFileSync)((0, node_path_1.resolve)(process.cwd(), path), 'utf8');
(0, node_test_1.test)('vendor store API client consumes existing Module 6 endpoints only', () => {
    const source = readSource('src/modules/vendor-stores/api/admin-vendor-store.api.ts');
    strict_1.default.match(source, /const ADMIN_VENDOR_BASE = '\/api\/v1\/admin\/vendors'/);
    strict_1.default.match(source, /const ADMIN_STORE_BASE = '\/api\/v1\/admin\/stores'/);
    strict_1.default.match(source, /apiClient\.get<ApiSuccessResponse<PaginatedAdminVendors>>/);
    strict_1.default.match(source, /`\$\{ADMIN_VENDOR_BASE\}\/\$\{vendorId\}`/);
    strict_1.default.match(source, /`\$\{ADMIN_VENDOR_BASE\}\/\$\{vendorId\}\/status`/);
    strict_1.default.match(source, /apiClient\.get<ApiSuccessResponse<PaginatedAdminStores>>/);
    strict_1.default.match(source, /`\$\{ADMIN_STORE_BASE\}\/\$\{storeId\}`/);
    strict_1.default.match(source, /`\$\{ADMIN_STORE_BASE\}\/\$\{storeId\}\/status`/);
    strict_1.default.match(source, /`\$\{ADMIN_STORE_BASE\}\/\$\{storeId\}\/orders`/);
    strict_1.default.match(source, /`\$\{ADMIN_STORE_BASE\}\/\$\{storeId\}\/inventory`/);
    strict_1.default.match(source, /`\$\{ADMIN_STORE_BASE\}\/\$\{storeId\}\/audit`/);
    strict_1.default.doesNotMatch(source, /\/create|\/delete|\/catalog|\/payouts|\/settlements/);
});
(0, node_test_1.test)('vendor store hooks expose query keys and mutation invalidation', () => {
    const vendorHookSource = readSource('src/modules/vendor-stores/hooks/useAdminVendors.ts');
    const storeHookSource = readSource('src/modules/vendor-stores/hooks/useAdminStores.ts');
    const mutationSource = readSource('src/modules/vendor-stores/hooks/useAdminVendorStoreMutations.ts');
    strict_1.default.match(vendorHookSource, /all: \['admin-vendor-stores'\]/);
    strict_1.default.match(vendorHookSource, /vendors: \(query: AdminVendorListQuery\)/);
    strict_1.default.match(vendorHookSource, /vendorDetail: \(vendorId: string\)/);
    strict_1.default.match(vendorHookSource, /storeOrders: \(storeId: string, query: unknown\)/);
    strict_1.default.match(storeHookSource, /useAdminStores/);
    strict_1.default.match(mutationSource, /useUpdateAdminVendorStatusMutation/);
    strict_1.default.match(mutationSource, /useUpdateAdminStoreStatusMutation/);
    strict_1.default.match(mutationSource, /invalidateQueries\(\{ queryKey: adminVendorStoreQueryKeys\.all \}\)/);
    strict_1.default.match(mutationSource, /adminVendorStoreQueryKeys\.vendorDetail\(vendorId\)/);
    strict_1.default.match(mutationSource, /adminVendorStoreQueryKeys\.storeDetail\(storeId\)/);
});
(0, node_test_1.test)('vendor store frontend types match documented filters and payloads', () => {
    const typeSource = readSource('src/modules/vendor-stores/types/admin-vendor-store.types.ts');
    const constantsSource = readSource('src/modules/vendor-stores/constants/admin-vendor-store.constants.ts');
    strict_1.default.match(typeSource, /export type AdminVendorListQuery = \{/);
    strict_1.default.match(typeSource, /status\?: VendorManagementStatus/);
    strict_1.default.match(typeSource, /cityId\?: string/);
    strict_1.default.match(typeSource, /search\?: string/);
    strict_1.default.match(typeSource, /export type AdminStoreListQuery = \{/);
    strict_1.default.match(typeSource, /vendorId\?: string/);
    strict_1.default.match(typeSource, /export type VendorStatusPayload = \{/);
    strict_1.default.match(typeSource, /export type StoreStatusPayload = \{/);
    strict_1.default.match(typeSource, /reason: string/);
    strict_1.default.match(constantsSource, /VENDOR_STATUS_OPTIONS/);
    strict_1.default.match(constantsSource, /STORE_STATUS_OPTIONS/);
});
(0, node_test_1.test)('vendors list page wires documented filters and pagination', () => {
    const routeSource = readSource('src/routes/admin.routes.tsx');
    const pageSource = readSource('src/pages/vendors/VendorsPage.tsx');
    const filterSource = readSource('src/modules/vendor-stores/components/VendorsFilterBar.tsx');
    const tableSource = readSource('src/modules/vendor-stores/components/VendorsTable.tsx');
    strict_1.default.match(routeSource, /path: '\/vendors'/);
    strict_1.default.match(routeSource, /permission="stores:read"/);
    strict_1.default.match(pageSource, /useAdminVendors\(filters\)/);
    strict_1.default.match(pageSource, /page: 1, limit: 20/);
    strict_1.default.match(pageSource, /pagination\.hasPreviousPage/);
    strict_1.default.match(pageSource, /pagination\.hasNextPage/);
    strict_1.default.match(filterSource, /status:/);
    strict_1.default.match(filterSource, /cityId:/);
    strict_1.default.match(filterSource, /search:/);
    strict_1.default.match(tableSource, /to=\{`\/vendors\/\$\{row\.vendorId\}`\}/);
});
(0, node_test_1.test)('vendor detail route and page use read-only detail contract', () => {
    const routeSource = readSource('src/routes/admin.routes.tsx');
    const detailSource = readSource('src/pages/vendors/VendorDetailPage.tsx');
    const summarySource = readSource('src/modules/vendor-stores/components/VendorSummary.tsx');
    strict_1.default.match(routeSource, /path: '\/vendors\/:vendorId'/);
    strict_1.default.match(routeSource, /permission="stores:read"/);
    strict_1.default.match(detailSource, /useParams<\{ vendorId: string \}>/);
    strict_1.default.match(detailSource, /useAdminVendorDetail\(vendorId\)/);
    strict_1.default.match(detailSource, /<VendorSummary vendor=\{detailQuery\.data\} \/>/);
    strict_1.default.match(summarySource, /primaryVendorUserId/);
    strict_1.default.match(summarySource, /accountStatus/);
    strict_1.default.match(summarySource, /storeCount/);
    strict_1.default.doesNotMatch(detailSource, /useUpdateAdminVendorStatusMutation/);
    strict_1.default.doesNotMatch(detailSource, /create|delete|catalog|payout|settlement/i);
});
(0, node_test_1.test)('vendor status control is permission-gated and submits status reason only', () => {
    const detailSource = readSource('src/pages/vendors/VendorDetailPage.tsx');
    const controlSource = readSource('src/modules/vendor-stores/components/VendorStatusControl.tsx');
    const schemaSource = readSource('src/modules/vendor-stores/validators/vendor-store-form.schema.ts');
    strict_1.default.match(detailSource, /VENDOR_STATUS_PERMISSIONS/);
    strict_1.default.match(detailSource, /'stores:update'/);
    strict_1.default.match(detailSource, /'settings:manage'/);
    strict_1.default.match(detailSource, /<CanAccessAny permissions=\{VENDOR_STATUS_PERMISSIONS\}>/);
    strict_1.default.match(detailSource, /<VendorStatusControl/);
    strict_1.default.match(controlSource, /useUpdateAdminVendorStatusMutation\(vendor\.vendorId\)/);
    strict_1.default.match(controlSource, /status: parsed\.data\.status/);
    strict_1.default.match(controlSource, /reason: parsed\.data\.reason/);
    strict_1.default.match(controlSource, /role="alert"/);
    strict_1.default.match(schemaSource, /vendorStatusFormSchema/);
    strict_1.default.match(schemaSource, /z\.string\(\)\.trim\(\)\.min\(5\)\.max\(500\)/);
    strict_1.default.doesNotMatch(controlSource, /deleted/);
    strict_1.default.doesNotMatch(controlSource, /profile|catalog|payout|settlement/i);
});
(0, node_test_1.test)('stores list page wires documented filters and pagination', () => {
    const routeSource = readSource('src/routes/store.routes.tsx');
    const pageSource = readSource('src/pages/stores/AdminStoresPage.tsx');
    const filterSource = readSource('src/modules/vendor-stores/components/StoresFilterBar.tsx');
    const tableSource = readSource('src/modules/vendor-stores/components/StoresTable.tsx');
    strict_1.default.match(routeSource, /path: '\/stores'/);
    strict_1.default.match(routeSource, /permission="stores:read"/);
    strict_1.default.match(routeSource, /<AdminStoresPage \/>/);
    strict_1.default.match(pageSource, /useAdminStores\(filters\)/);
    strict_1.default.match(pageSource, /page: 1, limit: 20/);
    strict_1.default.match(pageSource, /pagination\.hasPreviousPage/);
    strict_1.default.match(pageSource, /pagination\.hasNextPage/);
    strict_1.default.match(filterSource, /status:/);
    strict_1.default.match(filterSource, /vendorId:/);
    strict_1.default.match(filterSource, /cityId:/);
    strict_1.default.match(filterSource, /search:/);
    strict_1.default.match(tableSource, /to=\{`\/stores\/\$\{row\.storeId\}`\}/);
    strict_1.default.doesNotMatch(pageSource, /create|edit|delete|inventoryMutation|orderAction/i);
});
(0, node_test_1.test)('store detail route and page use read-only detail contract', () => {
    const routeSource = readSource('src/routes/store.routes.tsx');
    const detailSource = readSource('src/pages/stores/AdminStoreDetailPage.tsx');
    const summarySource = readSource('src/modules/vendor-stores/components/StoreSummary.tsx');
    strict_1.default.match(routeSource, /path: '\/stores\/:storeId'/);
    strict_1.default.match(routeSource, /permission="stores:read"/);
    strict_1.default.match(routeSource, /<AdminStoreDetailPage \/>/);
    strict_1.default.match(routeSource, /path: '\/stores\/:storeId\/edit'/);
    strict_1.default.match(detailSource, /useParams<\{ storeId: string \}>/);
    strict_1.default.match(detailSource, /useAdminStoreDetail\(storeId\)/);
    strict_1.default.match(detailSource, /<StoreSummary store=\{detailQuery\.data\} \/>/);
    strict_1.default.match(summarySource, /isOpen/);
    strict_1.default.match(summarySource, /isAcceptingOrders/);
    strict_1.default.match(summarySource, /temporaryClosureReason/);
    strict_1.default.doesNotMatch(detailSource, /useUpdateAdminStoreStatusMutation/);
    strict_1.default.doesNotMatch(detailSource, /catalog|inventoryMutation|orderAction|payout|settlement/i);
});
(0, node_test_1.test)('store detail page exposes read-only orders inventory and audit inspection', () => {
    const detailSource = readSource('src/pages/stores/AdminStoreDetailPage.tsx');
    const ordersTableSource = readSource('src/modules/vendor-stores/components/StoreOrdersTable.tsx');
    const inventoryTableSource = readSource('src/modules/vendor-stores/components/StoreInventoryTable.tsx');
    const auditTableSource = readSource('src/modules/vendor-stores/components/StoreAuditTable.tsx');
    strict_1.default.match(detailSource, /useAdminStoreOrders\(storeId, ordersQuery\)/);
    strict_1.default.match(detailSource, /useAdminStoreInventory\(storeId, inventoryQuery\)/);
    strict_1.default.match(detailSource, /useAdminStoreAudit\(storeId, auditQuery\)/);
    strict_1.default.match(detailSource, /orderPagination/);
    strict_1.default.match(detailSource, /inventoryPagination/);
    strict_1.default.match(detailSource, /auditPagination/);
    strict_1.default.match(ordersTableSource, /orderStatus/);
    strict_1.default.match(ordersTableSource, /paymentStatus/);
    strict_1.default.match(inventoryTableSource, /availableQuantity/);
    strict_1.default.match(inventoryTableSource, /reservedQuantity/);
    strict_1.default.match(auditTableSource, /actionType/);
    strict_1.default.match(auditTableSource, /adminId/);
    strict_1.default.match(auditTableSource, /reason/);
    strict_1.default.doesNotMatch(detailSource, /acceptOrder|rejectOrder|startPicking|adjustInventory|deleteAudit/i);
});
(0, node_test_1.test)('store status control is permission-gated and submits status reason only', () => {
    const detailSource = readSource('src/pages/stores/AdminStoreDetailPage.tsx');
    const controlSource = readSource('src/modules/vendor-stores/components/StoreStatusControl.tsx');
    const schemaSource = readSource('src/modules/vendor-stores/validators/vendor-store-form.schema.ts');
    strict_1.default.match(detailSource, /STORE_STATUS_PERMISSIONS/);
    strict_1.default.match(detailSource, /'stores:update'/);
    strict_1.default.match(detailSource, /'settings:manage'/);
    strict_1.default.match(detailSource, /<CanAccessAny permissions=\{STORE_STATUS_PERMISSIONS\}>/);
    strict_1.default.match(detailSource, /<StoreStatusControl/);
    strict_1.default.match(controlSource, /useUpdateAdminStoreStatusMutation\(store\.storeId\)/);
    strict_1.default.match(controlSource, /status: parsed\.data\.status/);
    strict_1.default.match(controlSource, /reason: parsed\.data\.reason/);
    strict_1.default.match(controlSource, /role="alert"/);
    strict_1.default.match(controlSource, /disabled=\{mutation\.isPending\}/);
    strict_1.default.match(controlSource, /loading=\{mutation\.isPending\}/);
    strict_1.default.match(schemaSource, /storeStatusFormSchema/);
    strict_1.default.doesNotMatch(controlSource, /isOpen|isAcceptingOrders|updateCatalog|adjustInventory|acceptOrder|rejectOrder|payout|settlement/i);
});
(0, node_test_1.test)('vendor store management UI avoids unsupported workflows', () => {
    const pageSource = [
        readSource('src/pages/vendors/VendorsPage.tsx'),
        readSource('src/pages/vendors/VendorDetailPage.tsx'),
        readSource('src/pages/stores/AdminStoresPage.tsx'),
        readSource('src/pages/stores/AdminStoreDetailPage.tsx'),
    ].join('\n');
    const apiSource = readSource('src/modules/vendor-stores/api/admin-vendor-store.api.ts');
    strict_1.default.match(pageSource, /ErrorView/);
    strict_1.default.match(pageSource, /EmptyState/);
    strict_1.default.doesNotMatch(pageSource, /acceptOrder|rejectOrder|startPicking|completePacking/i);
    strict_1.default.doesNotMatch(pageSource, /adjustInventory|updateCatalog|payout|settlement|supportTicket/i);
    strict_1.default.doesNotMatch(apiSource, /\/catalog|\/inventory\/adjust|\/orders\/.*\/status|\/payout|\/settlement|\/support/i);
});
