export const SOCKET_ERROR_CODES = {
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  INVALID_SOCKET_TOKEN: 'INVALID_SOCKET_TOKEN',
  SOCKET_FORBIDDEN: 'SOCKET_FORBIDDEN',
  ROOM_JOIN_DENIED: 'ROOM_JOIN_DENIED',
  SOCKET_SERVER_NOT_INITIALIZED: 'SOCKET_SERVER_NOT_INITIALIZED',
} as const;

export type SocketErrorCode = (typeof SOCKET_ERROR_CODES)[keyof typeof SOCKET_ERROR_CODES];
