"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const strict_1 = __importDefault(require("node:assert/strict"));
const node_fs_1 = require("node:fs");
const node_path_1 = require("node:path");
const node_test_1 = require("node:test");
const readSource = (path) => (0, node_fs_1.readFileSync)((0, node_path_1.resolve)(process.cwd(), path), 'utf8');
(0, node_test_1.test)('delivery agents API client uses existing Module 5 endpoints only', () => {
    const source = readSource('src/modules/delivery-agents/api/admin-delivery-agents.api.ts');
    strict_1.default.match(source, /const BASE = '\/api\/v1\/admin\/delivery-agents'/);
    strict_1.default.match(source, /apiClient\.get<ApiSuccessResponse<AdminDeliveryAgentListResponse>>/);
    strict_1.default.match(source, /`\$\{BASE\}\/\$\{deliveryAgentId\}`/);
    strict_1.default.match(source, /`\$\{BASE\}\/\$\{deliveryAgentId\}\/status`/);
    strict_1.default.match(source, /`\$\{BASE\}\/\$\{deliveryAgentId\}\/verification`/);
    strict_1.default.match(source, /`\$\{BASE\}\/\$\{deliveryAgentId\}\/assignments`/);
    strict_1.default.match(source, /`\$\{BASE\}\/\$\{deliveryAgentId\}\/audit`/);
});
(0, node_test_1.test)('delivery agent mutations refresh delivery-agent query keys', () => {
    const source = readSource('src/modules/delivery-agents/hooks/useAdminDeliveryAgentMutations.ts');
    strict_1.default.match(source, /invalidateQueries\(\{ queryKey: adminDeliveryAgentsQueryKeys\.all \}\)/);
    strict_1.default.match(source, /adminDeliveryAgentsQueryKeys\.detail\(deliveryAgentId\)/);
    strict_1.default.match(source, /useUpdateAdminDeliveryAgentStatusMutation/);
    strict_1.default.match(source, /useUpdateAdminDeliveryAgentVerificationMutation/);
});
(0, node_test_1.test)('delivery agents list page wires documented filters and pagination', () => {
    const pageSource = readSource('src/pages/delivery-agents/DeliveryAgentsPage.tsx');
    const filterSource = readSource('src/modules/delivery-agents/components/DeliveryAgentsFilterBar.tsx');
    strict_1.default.match(pageSource, /useAdminDeliveryAgents\(filters\)/);
    strict_1.default.match(pageSource, /page: 1, limit: 20/);
    strict_1.default.match(pageSource, /pagination\.hasPreviousPage/);
    strict_1.default.match(pageSource, /pagination\.hasNextPage/);
    strict_1.default.match(filterSource, /status:/);
    strict_1.default.match(filterSource, /availabilityStatus:/);
    strict_1.default.match(filterSource, /verificationStatus:/);
    strict_1.default.match(filterSource, /cityId:/);
    strict_1.default.match(filterSource, /search:/);
});
(0, node_test_1.test)('delivery agent detail route and page use read-only detail contract', () => {
    const routeSource = readSource('src/routes/admin.routes.tsx');
    const detailSource = readSource('src/pages/delivery-agents/DeliveryAgentDetailPage.tsx');
    const summarySource = readSource('src/modules/delivery-agents/components/DeliveryAgentSummary.tsx');
    strict_1.default.match(routeSource, /path: '\/delivery-agents\/:deliveryAgentId'/);
    strict_1.default.match(routeSource, /permission="delivery:read"/);
    strict_1.default.match(detailSource, /useParams<\{ deliveryAgentId: string \}>/);
    strict_1.default.match(detailSource, /useAdminDeliveryAgentDetail\(deliveryAgentId\)/);
    strict_1.default.match(detailSource, /<DeliveryAgentSummary agent=\{detailQuery\.data\} \/>/);
    strict_1.default.match(summarySource, /forcedOfflineReason/);
    strict_1.default.match(summarySource, /currentAssignmentId/);
    strict_1.default.doesNotMatch(detailSource, /useUpdateAdminDeliveryAgentStatusMutation/);
    strict_1.default.doesNotMatch(detailSource, /useUpdateAdminDeliveryAgentVerificationMutation/);
});
(0, node_test_1.test)('delivery agent detail page exposes read-only assignment inspection', () => {
    const detailSource = readSource('src/pages/delivery-agents/DeliveryAgentDetailPage.tsx');
    const filterSource = readSource('src/modules/delivery-agents/components/DeliveryAgentAssignmentsFilterBar.tsx');
    const tableSource = readSource('src/modules/delivery-agents/components/DeliveryAgentAssignmentsTable.tsx');
    strict_1.default.match(detailSource, /useAdminDeliveryAgentAssignments\(deliveryAgentId, assignmentFilters\)/);
    strict_1.default.match(detailSource, /page: 1,\s+limit: 20/);
    strict_1.default.match(detailSource, /assignmentPagination\.hasPreviousPage/);
    strict_1.default.match(detailSource, /assignmentPagination\.hasNextPage/);
    strict_1.default.match(filterSource, /status:/);
    strict_1.default.match(filterSource, /fromDate:/);
    strict_1.default.match(filterSource, /toDate:/);
    strict_1.default.match(tableSource, /deliveryId/);
    strict_1.default.match(tableSource, /orderId/);
    strict_1.default.match(tableSource, /deliveryStatus/);
    strict_1.default.match(tableSource, /assignmentSource/);
    strict_1.default.match(tableSource, /assignedAt/);
    strict_1.default.match(tableSource, /pickedUpAt/);
    strict_1.default.match(tableSource, /completedAt/);
    strict_1.default.doesNotMatch(detailSource, /reassign|unassign|override/);
});
(0, node_test_1.test)('delivery agent detail page exposes read-only audit inspection', () => {
    const detailSource = readSource('src/pages/delivery-agents/DeliveryAgentDetailPage.tsx');
    const tableSource = readSource('src/modules/delivery-agents/components/DeliveryAgentAuditTable.tsx');
    strict_1.default.match(detailSource, /useAdminDeliveryAgentAudit\(deliveryAgentId, auditFilters\)/);
    strict_1.default.match(detailSource, /setAuditFilters/);
    strict_1.default.match(detailSource, /auditPagination\.hasPreviousPage/);
    strict_1.default.match(detailSource, /auditPagination\.hasNextPage/);
    strict_1.default.match(tableSource, /actionType/);
    strict_1.default.match(tableSource, /adminId/);
    strict_1.default.match(tableSource, /reason/);
    strict_1.default.match(tableSource, /ipAddress/);
    strict_1.default.match(tableSource, /deviceInfo/);
    strict_1.default.match(tableSource, /createdAt/);
    strict_1.default.doesNotMatch(tableSource, /beforeState|afterState/);
});
(0, node_test_1.test)('delivery agent status control is permission-gated and submits status reason only', () => {
    const detailSource = readSource('src/pages/delivery-agents/DeliveryAgentDetailPage.tsx');
    const controlSource = readSource('src/modules/delivery-agents/components/DeliveryAgentStatusControl.tsx');
    const schemaSource = readSource('src/modules/delivery-agents/validators/delivery-agent-form.schema.ts');
    strict_1.default.match(detailSource, /DELIVERY_AGENT_STATUS_PERMISSIONS/);
    strict_1.default.match(detailSource, /'delivery:update-status'/);
    strict_1.default.match(detailSource, /'settings:manage'/);
    strict_1.default.match(detailSource, /<CanAccessAny permissions=\{DELIVERY_AGENT_STATUS_PERMISSIONS\}>/);
    strict_1.default.match(detailSource, /<DeliveryAgentStatusControl/);
    strict_1.default.match(controlSource, /useUpdateAdminDeliveryAgentStatusMutation\(agent\.agentId\)/);
    strict_1.default.match(controlSource, /status: parsed\.data\.status/);
    strict_1.default.match(controlSource, /reason: parsed\.data\.reason/);
    strict_1.default.match(controlSource, /role="alert"/);
    strict_1.default.match(schemaSource, /deliveryAgentStatusFormSchema/);
    strict_1.default.match(schemaSource, /z\.string\(\)\.trim\(\)\.min\(5\)\.max\(500\)/);
    strict_1.default.doesNotMatch(controlSource, /verificationStatus/);
});
(0, node_test_1.test)('delivery agent verification control is permission-gated and submits verification reason only', () => {
    const detailSource = readSource('src/pages/delivery-agents/DeliveryAgentDetailPage.tsx');
    const controlSource = readSource('src/modules/delivery-agents/components/DeliveryAgentVerificationControl.tsx');
    const schemaSource = readSource('src/modules/delivery-agents/validators/delivery-agent-form.schema.ts');
    strict_1.default.match(detailSource, /DELIVERY_AGENT_VERIFICATION_PERMISSIONS/);
    strict_1.default.match(detailSource, /'delivery:update'/);
    strict_1.default.match(detailSource, /'settings:manage'/);
    strict_1.default.match(detailSource, /<CanAccessAny permissions=\{DELIVERY_AGENT_VERIFICATION_PERMISSIONS\}>/);
    strict_1.default.match(detailSource, /<DeliveryAgentVerificationControl/);
    strict_1.default.match(controlSource, /useUpdateAdminDeliveryAgentVerificationMutation\(agent\.agentId\)/);
    strict_1.default.match(controlSource, /verificationStatus: parsed\.data\.verificationStatus/);
    strict_1.default.match(controlSource, /reason: parsed\.data\.reason/);
    strict_1.default.match(controlSource, /role="alert"/);
    strict_1.default.match(schemaSource, /deliveryAgentVerificationFormSchema/);
    strict_1.default.match(schemaSource, /verificationStatus: z\.enum\(verificationValues\)/);
    strict_1.default.doesNotMatch(controlSource, /status: parsed\.data\.status/);
});
(0, node_test_1.test)('delivery agent management UI keeps mutations guarded and avoids unsupported operations', () => {
    const pageSource = readSource('src/pages/delivery-agents/DeliveryAgentDetailPage.tsx');
    const statusControlSource = readSource('src/modules/delivery-agents/components/DeliveryAgentStatusControl.tsx');
    const verificationControlSource = readSource('src/modules/delivery-agents/components/DeliveryAgentVerificationControl.tsx');
    const assignmentsTableSource = readSource('src/modules/delivery-agents/components/DeliveryAgentAssignmentsTable.tsx');
    const apiSource = readSource('src/modules/delivery-agents/api/admin-delivery-agents.api.ts');
    strict_1.default.match(pageSource, /ErrorView/);
    strict_1.default.match(pageSource, /EmptyState/);
    strict_1.default.match(statusControlSource, /disabled=\{mutation\.isPending\}/);
    strict_1.default.match(statusControlSource, /loading=\{mutation\.isPending\}/);
    strict_1.default.match(verificationControlSource, /disabled=\{mutation\.isPending\}/);
    strict_1.default.match(verificationControlSource, /loading=\{mutation\.isPending\}/);
    strict_1.default.doesNotMatch(assignmentsTableSource, /reassign|unassign|override|dispatch/i);
    strict_1.default.doesNotMatch(apiSource, /payroll|incentive|exportCsv|exportPdf|analytics|supportTicket/i);
});
