export const STORE_PRODUCT_ERROR_CODES = {
  STORE_PRODUCT_NOT_FOUND: 'STORE_PRODUCT_NOT_FOUND',
  STORE_PRODUCT_ALREADY_MAPPED: 'STORE_PRODUCT_ALREADY_MAPPED',
  STORE_PRODUCT_SKU_ALREADY_EXISTS: 'STORE_PRODUCT_SKU_ALREADY_EXISTS',
  INVALID_STORE_PRODUCT_STORE: 'INVALID_STORE_PRODUCT_STORE',
  INVALID_STORE_PRODUCT_PRODUCT: 'INVALID_STORE_PRODUCT_PRODUCT',
  INVALID_STORE_PRODUCT_VARIANT: 'INVALID_STORE_PRODUCT_VARIANT',
  STORE_PRODUCT_VARIANT_MISMATCH: 'STORE_PRODUCT_VARIANT_MISMATCH',
  STORE_PRODUCT_PRICE_INVALID: 'STORE_PRODUCT_PRICE_INVALID',
  STORE_PRODUCT_FINAL_PRICE_INVALID: 'STORE_PRODUCT_FINAL_PRICE_INVALID',
  STORE_PRODUCT_PRICE_LOCKED: 'STORE_PRODUCT_PRICE_LOCKED',
  STORE_PRODUCT_SCOPE_DENIED: 'STORE_PRODUCT_SCOPE_DENIED',
  STORE_PRODUCT_BULK_VALIDATION_FAILED: 'STORE_PRODUCT_BULK_VALIDATION_FAILED',
  STORE_PRODUCT_HAS_INVENTORY_STOCK: 'STORE_PRODUCT_HAS_INVENTORY_STOCK',
} as const;

export type StoreProductErrorCode =
  (typeof STORE_PRODUCT_ERROR_CODES)[keyof typeof STORE_PRODUCT_ERROR_CODES];
