export const STORE_PRODUCT_BULK_DUPLICATE_MODE = {
  FAIL: 'fail',
  SKIP: 'skip',
  REPLACE: 'replace',
} as const;

export type StoreProductBulkDuplicateMode =
  (typeof STORE_PRODUCT_BULK_DUPLICATE_MODE)[keyof typeof STORE_PRODUCT_BULK_DUPLICATE_MODE];

export const STORE_PRODUCT_BULK_DUPLICATE_MODE_VALUES = [
  STORE_PRODUCT_BULK_DUPLICATE_MODE.FAIL,
  STORE_PRODUCT_BULK_DUPLICATE_MODE.SKIP,
  STORE_PRODUCT_BULK_DUPLICATE_MODE.REPLACE,
] as const;
