export const INVENTORY_REFERENCE_TYPE = {
  MANUAL: 'manual',
  ORDER: 'order',
  CART: 'cart',
  RETURN: 'return',
  SYSTEM: 'system',
  SEED: 'seed',
  IMPORT: 'import',
} as const;

export const INVENTORY_REFERENCE_TYPE_VALUES = [
  INVENTORY_REFERENCE_TYPE.MANUAL,
  INVENTORY_REFERENCE_TYPE.ORDER,
  INVENTORY_REFERENCE_TYPE.CART,
  INVENTORY_REFERENCE_TYPE.RETURN,
  INVENTORY_REFERENCE_TYPE.SYSTEM,
  INVENTORY_REFERENCE_TYPE.SEED,
  INVENTORY_REFERENCE_TYPE.IMPORT,
] as const;

export type InventoryReferenceType = (typeof INVENTORY_REFERENCE_TYPE_VALUES)[number];
