export const INVENTORY_MOVEMENT_TYPE = {
  STOCK_IN: 'stock_in',
  STOCK_OUT: 'stock_out',
  MANUAL_ADJUSTMENT: 'manual_adjustment',
  RESERVATION_CREATED: 'reservation_created',
  RESERVATION_RELEASED: 'reservation_released',
  RESERVATION_CONFIRMED: 'reservation_confirmed',
  DAMAGED: 'damaged',
  EXPIRED: 'expired',
  CORRECTION: 'correction',
} as const;

export const INVENTORY_MOVEMENT_TYPE_VALUES = [
  INVENTORY_MOVEMENT_TYPE.STOCK_IN,
  INVENTORY_MOVEMENT_TYPE.STOCK_OUT,
  INVENTORY_MOVEMENT_TYPE.MANUAL_ADJUSTMENT,
  INVENTORY_MOVEMENT_TYPE.RESERVATION_CREATED,
  INVENTORY_MOVEMENT_TYPE.RESERVATION_RELEASED,
  INVENTORY_MOVEMENT_TYPE.RESERVATION_CONFIRMED,
  INVENTORY_MOVEMENT_TYPE.DAMAGED,
  INVENTORY_MOVEMENT_TYPE.EXPIRED,
  INVENTORY_MOVEMENT_TYPE.CORRECTION,
] as const;

export const ADMIN_INVENTORY_ADJUSTMENT_TYPES = [
  INVENTORY_MOVEMENT_TYPE.STOCK_IN,
  INVENTORY_MOVEMENT_TYPE.STOCK_OUT,
  INVENTORY_MOVEMENT_TYPE.MANUAL_ADJUSTMENT,
  INVENTORY_MOVEMENT_TYPE.DAMAGED,
  INVENTORY_MOVEMENT_TYPE.EXPIRED,
  INVENTORY_MOVEMENT_TYPE.CORRECTION,
] as const;

export const VENDOR_INVENTORY_ADJUSTMENT_TYPES = [
  INVENTORY_MOVEMENT_TYPE.STOCK_IN,
  INVENTORY_MOVEMENT_TYPE.STOCK_OUT,
  INVENTORY_MOVEMENT_TYPE.DAMAGED,
  INVENTORY_MOVEMENT_TYPE.EXPIRED,
  INVENTORY_MOVEMENT_TYPE.CORRECTION,
] as const;

export type InventoryMovementType = (typeof INVENTORY_MOVEMENT_TYPE_VALUES)[number];
