export const PUSH_NOTIFICATION_ERROR_CODES = {
  DEVICE_TOKEN_NOT_FOUND: 'DEVICE_TOKEN_NOT_FOUND',
  INVALID_FCM_TOKEN: 'INVALID_FCM_TOKEN',
  PUSH_PROVIDER_NOT_CONFIGURED: 'PUSH_PROVIDER_NOT_CONFIGURED',
  PUSH_SEND_FAILED: 'PUSH_SEND_FAILED',
  INVALID_PUSH_PLATFORM: 'INVALID_PUSH_PLATFORM',
} as const;

export type PushNotificationErrorCode =
  (typeof PUSH_NOTIFICATION_ERROR_CODES)[keyof typeof PUSH_NOTIFICATION_ERROR_CODES];
