export const VARIANT_ERROR_CODES = {
  VARIANT_NOT_FOUND: 'VARIANT_NOT_FOUND',
  SKU_ALREADY_EXISTS: 'SKU_ALREADY_EXISTS',
  BARCODE_ALREADY_EXISTS: 'BARCODE_ALREADY_EXISTS',
  DEFAULT_VARIANT_REQUIRED: 'DEFAULT_VARIANT_REQUIRED',
  INVALID_VARIANT_UNIT: 'INVALID_VARIANT_UNIT',
  VARIANT_HAS_ACTIVE_STORE_MAPPINGS: 'VARIANT_HAS_ACTIVE_STORE_MAPPINGS',
} as const;

export type VariantErrorCode = (typeof VARIANT_ERROR_CODES)[keyof typeof VARIANT_ERROR_CODES];
