"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.typography = exports.spacing = exports.shadows = exports.radius = exports.colors = void 0;
var colors_1 = require("./colors");
Object.defineProperty(exports, "colors", { enumerable: true, get: function () { return colors_1.colors; } });
var radius_1 = require("./radius");
Object.defineProperty(exports, "radius", { enumerable: true, get: function () { return radius_1.radius; } });
var shadows_1 = require("./shadows");
Object.defineProperty(exports, "shadows", { enumerable: true, get: function () { return shadows_1.shadows; } });
var spacing_1 = require("./spacing");
Object.defineProperty(exports, "spacing", { enumerable: true, get: function () { return spacing_1.spacing; } });
var typography_1 = require("./typography");
Object.defineProperty(exports, "typography", { enumerable: true, get: function () { return typography_1.typography; } });
