export const MEDIA_ERROR_CODES = {
  MEDIA_FILE_NOT_FOUND: 'MEDIA_FILE_NOT_FOUND',
  MEDIA_UPLOAD_FAILED: 'MEDIA_UPLOAD_FAILED',
  MEDIA_DELETE_FAILED: 'MEDIA_DELETE_FAILED',
  MEDIA_INVALID_MIME_TYPE: 'MEDIA_INVALID_MIME_TYPE',
  MEDIA_INVALID_EXTENSION: 'MEDIA_INVALID_EXTENSION',
  MEDIA_FILE_TOO_LARGE: 'MEDIA_FILE_TOO_LARGE',
  MEDIA_FILE_EMPTY: 'MEDIA_FILE_EMPTY',
  MEDIA_FILE_COUNT_EXCEEDED: 'MEDIA_FILE_COUNT_EXCEEDED',
  MEDIA_STORAGE_PROVIDER_INVALID: 'MEDIA_STORAGE_PROVIDER_INVALID',
  MEDIA_ACCESS_DENIED: 'MEDIA_ACCESS_DENIED',
  MEDIA_OWNER_INVALID: 'MEDIA_OWNER_INVALID',
  MEDIA_SIGNED_URL_FAILED: 'MEDIA_SIGNED_URL_FAILED',
} as const;

export type MediaErrorCode = (typeof MEDIA_ERROR_CODES)[keyof typeof MEDIA_ERROR_CODES];
