export const MEDIA_FILE_PURPOSE = {
  CATEGORY_ICON: 'category_icon',
  CATEGORY_BANNER: 'category_banner',
  BRAND_LOGO: 'brand_logo',
  BRAND_BANNER: 'brand_banner',
  PRODUCT_MAIN_IMAGE: 'product_main_image',
  PRODUCT_GALLERY_IMAGE: 'product_gallery_image',
  VARIANT_IMAGE: 'variant_image',
  STORE_LOGO: 'store_logo',
  STORE_BANNER: 'store_banner',
  PROFILE_IMAGE: 'profile_image',
  ORDER_PROOF: 'order_proof',
  SUPPORT_ATTACHMENT: 'support_attachment',
  DOCUMENT_UPLOAD: 'document_upload',
  GENERAL: 'general',
} as const;

export const MEDIA_FILE_PURPOSE_VALUES = [
  MEDIA_FILE_PURPOSE.CATEGORY_ICON,
  MEDIA_FILE_PURPOSE.CATEGORY_BANNER,
  MEDIA_FILE_PURPOSE.BRAND_LOGO,
  MEDIA_FILE_PURPOSE.BRAND_BANNER,
  MEDIA_FILE_PURPOSE.PRODUCT_MAIN_IMAGE,
  MEDIA_FILE_PURPOSE.PRODUCT_GALLERY_IMAGE,
  MEDIA_FILE_PURPOSE.VARIANT_IMAGE,
  MEDIA_FILE_PURPOSE.STORE_LOGO,
  MEDIA_FILE_PURPOSE.STORE_BANNER,
  MEDIA_FILE_PURPOSE.PROFILE_IMAGE,
  MEDIA_FILE_PURPOSE.ORDER_PROOF,
  MEDIA_FILE_PURPOSE.SUPPORT_ATTACHMENT,
  MEDIA_FILE_PURPOSE.DOCUMENT_UPLOAD,
  MEDIA_FILE_PURPOSE.GENERAL,
] as const;

export type MediaFilePurpose = (typeof MEDIA_FILE_PURPOSE_VALUES)[number];
