export const CATALOG_SEARCH_ERROR_CODES = {
  CATALOG_SEARCH_QUERY_TOO_LONG: 'CATALOG_SEARCH_QUERY_TOO_LONG',
  CATALOG_SEARCH_INVALID_SORT: 'CATALOG_SEARCH_INVALID_SORT',
  CATALOG_SEARCH_INVALID_FILTER: 'CATALOG_SEARCH_INVALID_FILTER',
  CATALOG_SEARCH_PRICE_RANGE_INVALID: 'CATALOG_SEARCH_PRICE_RANGE_INVALID',
  CATALOG_SEARCH_SCOPE_DENIED: 'CATALOG_SEARCH_SCOPE_DENIED',
  CATALOG_SEARCH_FAILED: 'CATALOG_SEARCH_FAILED',
} as const;

export type CatalogSearchErrorCode =
  (typeof CATALOG_SEARCH_ERROR_CODES)[keyof typeof CATALOG_SEARCH_ERROR_CODES];
