export const CATALOG_FILTER_KEYS = [
  'categoryId',
  'subcategoryId',
  'brandId',
  'foodType',
  'productType',
  'approvalStatus',
  'status',
  'isVisible',
  'isFeatured',
  'isAvailable',
  'isOutOfStock',
  'minPrice',
  'maxPrice',
  'storeId',
  'cityId',
  'vendorId',
  'search',
  'q',
] as const;
