export const BRAND_ERROR_CODES = {
  BRAND_NOT_FOUND: 'BRAND_NOT_FOUND',
  BRAND_SLUG_ALREADY_EXISTS: 'BRAND_SLUG_ALREADY_EXISTS',
  BRAND_HAS_ACTIVE_PRODUCTS: 'BRAND_HAS_ACTIVE_PRODUCTS',
  INVALID_BRAND_STATUS: 'INVALID_BRAND_STATUS',
} as const;

export type BrandErrorCode = (typeof BRAND_ERROR_CODES)[keyof typeof BRAND_ERROR_CODES];
