export const INVENTORY_ERROR_CODES = {
  INVENTORY_STOCK_NOT_FOUND: 'INVENTORY_STOCK_NOT_FOUND',
  INVENTORY_STOCK_ALREADY_EXISTS: 'INVENTORY_STOCK_ALREADY_EXISTS',
  INVALID_INVENTORY_STORE_PRODUCT: 'INVALID_INVENTORY_STORE_PRODUCT',
  INVALID_INVENTORY_QUANTITY: 'INVALID_INVENTORY_QUANTITY',
  INSUFFICIENT_AVAILABLE_STOCK: 'INSUFFICIENT_AVAILABLE_STOCK',
  INVENTORY_RESERVED_STOCK_EXISTS: 'INVENTORY_RESERVED_STOCK_EXISTS',
  INVENTORY_SCOPE_DENIED: 'INVENTORY_SCOPE_DENIED',
  INVENTORY_BULK_VALIDATION_FAILED: 'INVENTORY_BULK_VALIDATION_FAILED',
  INVALID_INVENTORY_STATUS: 'INVALID_INVENTORY_STATUS',
  INVALID_INVENTORY_MOVEMENT_TYPE: 'INVALID_INVENTORY_MOVEMENT_TYPE',
  INVALID_INVENTORY_REFERENCE_TYPE: 'INVALID_INVENTORY_REFERENCE_TYPE',
} as const;

export type InventoryErrorCode =
  (typeof INVENTORY_ERROR_CODES)[keyof typeof INVENTORY_ERROR_CODES];
