"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const strict_1 = __importDefault(require("node:assert/strict"));
const node_fs_1 = require("node:fs");
const node_path_1 = require("node:path");
const node_test_1 = require("node:test");
const apiSource = () => (0, node_fs_1.readFileSync)((0, node_path_1.resolve)(process.cwd(), 'src/modules/support/api/support.api.ts'), 'utf8');
const hooksSource = () => (0, node_fs_1.readFileSync)((0, node_path_1.resolve)(process.cwd(), 'src/modules/support/hooks/useSupportTicketMutations.ts'), 'utf8');
(0, node_test_1.test)('support API client uses Module 12 support endpoints only', () => {
    const source = apiSource();
    strict_1.default.match(source, /const BASE = '\/api\/v1\/admin\/support\/tickets'/);
    strict_1.default.match(source, /apiClient\.get<ApiSuccessResponse<SupportTicketListResponse>>\(BASE/);
    strict_1.default.match(source, /apiClient\.post<ApiSuccessResponse<SupportTicket>>\(BASE, payload\)/);
    strict_1.default.match(source, /`\$\{BASE\}\/\$\{ticketId\}`/);
    strict_1.default.match(source, /`\$\{BASE\}\/\$\{ticketId\}\/status`/);
    strict_1.default.match(source, /`\$\{BASE\}\/\$\{ticketId\}\/priority`/);
    strict_1.default.match(source, /`\$\{BASE\}\/\$\{ticketId\}\/assignment`/);
    strict_1.default.match(source, /`\$\{BASE\}\/\$\{ticketId\}\/notes`/);
    strict_1.default.match(source, /`\$\{BASE\}\/\$\{ticketId\}\/audit`/);
    strict_1.default.doesNotMatch(source, /refund|chat|attachment|realtime|\/orders\/.*\/status|\/delivery|\/customers\/.*\/status/i);
});
(0, node_test_1.test)('support mutations refresh list detail notes and audit query keys', () => {
    const source = hooksSource();
    strict_1.default.match(source, /invalidateQueries\(\{ queryKey: supportQueryKeys\.all \}\)/);
    strict_1.default.match(source, /invalidateQueries\(\{ queryKey: supportQueryKeys\.detail\(ticketId\) \}\)/);
    strict_1.default.match(source, /invalidateQueries\(\{ queryKey: supportQueryKeys\.notes\(ticketId\) \}\)/);
    strict_1.default.match(source, /invalidateQueries\(\{ queryKey: supportQueryKeys\.audit\(ticketId\) \}\)/);
});
(0, node_test_1.test)('support list page wires documented filters and pagination', () => {
    const pageSource = (0, node_fs_1.readFileSync)((0, node_path_1.resolve)(process.cwd(), 'src/pages/support/SupportPage.tsx'), 'utf8');
    const filterSource = (0, node_fs_1.readFileSync)((0, node_path_1.resolve)(process.cwd(), 'src/modules/support/components/SupportTicketFilterBar.tsx'), 'utf8');
    const tableSource = (0, node_fs_1.readFileSync)((0, node_path_1.resolve)(process.cwd(), 'src/modules/support/components/SupportTicketTable.tsx'), 'utf8');
    strict_1.default.match(pageSource, /useSupportTickets\(filters\)/);
    strict_1.default.match(pageSource, /page: 1, limit: 20/);
    strict_1.default.match(pageSource, /pagination\.hasPreviousPage/);
    strict_1.default.match(pageSource, /pagination\.hasNextPage/);
    strict_1.default.match(filterSource, /status:/);
    strict_1.default.match(filterSource, /priority:/);
    strict_1.default.match(filterSource, /category:/);
    strict_1.default.match(filterSource, /customerId:/);
    strict_1.default.match(filterSource, /orderId:/);
    strict_1.default.match(filterSource, /assignedAdminId:/);
    strict_1.default.match(filterSource, /search:/);
    strict_1.default.match(tableSource, /\/support\/tickets\/\$\{row\.ticketId\}/);
});
(0, node_test_1.test)('support detail route fetches ticket detail endpoint only', () => {
    const routesSource = (0, node_fs_1.readFileSync)((0, node_path_1.resolve)(process.cwd(), 'src/routes/admin.routes.tsx'), 'utf8');
    const detailSource = (0, node_fs_1.readFileSync)((0, node_path_1.resolve)(process.cwd(), 'src/modules/support/pages/SupportTicketDetailPage.tsx'), 'utf8');
    const summarySource = (0, node_fs_1.readFileSync)((0, node_path_1.resolve)(process.cwd(), 'src/modules/support/components/SupportTicketSummary.tsx'), 'utf8');
    strict_1.default.match(routesSource, /path: '\/support\/tickets\/:ticketId'/);
    strict_1.default.match(routesSource, /permission="support:read"/);
    strict_1.default.match(detailSource, /useSupportTicketDetail\(ticketId\)/);
    strict_1.default.match(summarySource, /SupportTicketStatusBadge/);
    strict_1.default.match(summarySource, /SupportTicketPriorityBadge/);
    strict_1.default.doesNotMatch(detailSource, /useUpdateSupportTicket|useCreateSupportTicketNote/);
});
(0, node_test_1.test)('create support ticket UI is permission gated and submits create payload only', () => {
    const pageSource = (0, node_fs_1.readFileSync)((0, node_path_1.resolve)(process.cwd(), 'src/pages/support/SupportPage.tsx'), 'utf8');
    const modalSource = (0, node_fs_1.readFileSync)((0, node_path_1.resolve)(process.cwd(), 'src/modules/support/components/CreateSupportTicketModal.tsx'), 'utf8');
    strict_1.default.match(pageSource, /SUPPORT_TICKET_CREATE_PERMISSIONS = \['support:create', 'settings:manage'\]/);
    strict_1.default.match(pageSource, /<CreateSupportTicketModal/);
    strict_1.default.match(modalSource, /useCreateSupportTicketMutation/);
    strict_1.default.match(modalSource, /createSupportTicketFormSchema\.safeParse\(values\)/);
    strict_1.default.match(modalSource, /mutation\.mutate\(payload/);
    strict_1.default.match(modalSource, /customerId: parsed\.data\.customerId/);
    strict_1.default.match(modalSource, /orderId: parsed\.data\.orderId/);
    strict_1.default.doesNotMatch(modalSource, /reason:/);
    strict_1.default.doesNotMatch(modalSource, /refund|chat|attachment|realtime/i);
});
(0, node_test_1.test)('support ticket mutation controls are permission gated and require reason', () => {
    const detailSource = (0, node_fs_1.readFileSync)((0, node_path_1.resolve)(process.cwd(), 'src/modules/support/pages/SupportTicketDetailPage.tsx'), 'utf8');
    const statusSource = (0, node_fs_1.readFileSync)((0, node_path_1.resolve)(process.cwd(), 'src/modules/support/components/SupportTicketStatusControl.tsx'), 'utf8');
    const prioritySource = (0, node_fs_1.readFileSync)((0, node_path_1.resolve)(process.cwd(), 'src/modules/support/components/SupportTicketPriorityControl.tsx'), 'utf8');
    const assignmentSource = (0, node_fs_1.readFileSync)((0, node_path_1.resolve)(process.cwd(), 'src/modules/support/components/SupportTicketAssignmentControl.tsx'), 'utf8');
    strict_1.default.match(detailSource, /SUPPORT_TICKET_UPDATE_PERMISSIONS = \['support:update', 'settings:manage'\]/);
    strict_1.default.match(detailSource, /SUPPORT_TICKET_ASSIGN_PERMISSIONS = \['support:assign', 'settings:manage'\]/);
    strict_1.default.match(statusSource, /useUpdateSupportTicketStatusMutation\(ticket\.ticketId\)/);
    strict_1.default.match(statusSource, /supportTicketStatusFormSchema\.safeParse\(values\)/);
    strict_1.default.match(statusSource, /reason: parsed\.data\.reason/);
    strict_1.default.match(prioritySource, /useUpdateSupportTicketPriorityMutation\(ticket\.ticketId\)/);
    strict_1.default.match(prioritySource, /supportTicketPriorityFormSchema\.safeParse\(values\)/);
    strict_1.default.match(prioritySource, /reason: parsed\.data\.reason/);
    strict_1.default.match(assignmentSource, /useUpdateSupportTicketAssignmentMutation\(ticket\.ticketId\)/);
    strict_1.default.match(assignmentSource, /supportTicketAssignmentFormSchema\.safeParse\(values\)/);
    strict_1.default.match(assignmentSource, /assignedAdminId: parsed\.data\.assignedAdminId/);
    strict_1.default.match(assignmentSource, /reason: parsed\.data\.reason/);
});
(0, node_test_1.test)('support ticket notes and audit panels use notes and audit endpoints only', () => {
    const detailSource = (0, node_fs_1.readFileSync)((0, node_path_1.resolve)(process.cwd(), 'src/modules/support/pages/SupportTicketDetailPage.tsx'), 'utf8');
    const notesSource = (0, node_fs_1.readFileSync)((0, node_path_1.resolve)(process.cwd(), 'src/modules/support/components/SupportTicketNotesPanel.tsx'), 'utf8');
    const auditSource = (0, node_fs_1.readFileSync)((0, node_path_1.resolve)(process.cwd(), 'src/modules/support/components/SupportTicketAuditTable.tsx'), 'utf8');
    strict_1.default.match(detailSource, /<SupportTicketNotesPanel ticketId=\{ticket\.ticketId\}/);
    strict_1.default.match(detailSource, /<SupportTicketAuditTable ticketId=\{ticket\.ticketId\}/);
    strict_1.default.match(notesSource, /useSupportTicketNotes\(ticketId\)/);
    strict_1.default.match(notesSource, /useCreateSupportTicketNoteMutation\(ticketId\)/);
    strict_1.default.match(notesSource, /SUPPORT_TICKET_NOTE_CREATE_PERMISSIONS = \['support:update', 'settings:manage'\]/);
    strict_1.default.match(notesSource, /supportTicketNoteFormSchema\.safeParse\(values\)/);
    strict_1.default.match(auditSource, /useSupportTicketAudit\(ticketId\)/);
    strict_1.default.doesNotMatch(auditSource, /useCreate|useUpdate|apiClient\.(post|patch|put|delete)/);
});
(0, node_test_1.test)('support operations UI is permission gated and excludes future-module workflows', () => {
    const routesSource = (0, node_fs_1.readFileSync)((0, node_path_1.resolve)(process.cwd(), 'src/routes/admin.routes.tsx'), 'utf8');
    const sidebarSource = (0, node_fs_1.readFileSync)((0, node_path_1.resolve)(process.cwd(), 'src/components/layout/Sidebar.tsx'), 'utf8');
    const pageSource = (0, node_fs_1.readFileSync)((0, node_path_1.resolve)(process.cwd(), 'src/pages/support/SupportPage.tsx'), 'utf8');
    const detailSource = (0, node_fs_1.readFileSync)((0, node_path_1.resolve)(process.cwd(), 'src/modules/support/pages/SupportTicketDetailPage.tsx'), 'utf8');
    const apiSourceText = apiSource();
    strict_1.default.match(routesSource, /path: '\/support'/);
    strict_1.default.match(routesSource, /path: '\/support\/tickets\/:ticketId'/);
    strict_1.default.match(routesSource, /permission="support:read"/);
    strict_1.default.match(sidebarSource, /\{ label: 'Support', to: '\/support', permission: 'support:read' \}/);
    strict_1.default.match(pageSource, /SUPPORT_TICKET_CREATE_PERMISSIONS = \['support:create', 'settings:manage'\]/);
    strict_1.default.match(detailSource, /SUPPORT_TICKET_UPDATE_PERMISSIONS = \['support:update', 'settings:manage'\]/);
    strict_1.default.match(detailSource, /SUPPORT_TICKET_ASSIGN_PERMISSIONS = \['support:assign', 'settings:manage'\]/);
    strict_1.default.doesNotMatch(apiSourceText, /refund|chat|attachment|realtime|\/orders\/.*\/status|\/delivery|\/customers\/.*\/status/i);
    strict_1.default.doesNotMatch(`${pageSource}\n${detailSource}`, /Refund|Chat|Attachment|Realtime|Customer status/i);
});
