import { AUTH_ROLE } from '../../modules/auth/constants/auth-role.constants';
import {
  AUTH_PERMISSION_ACTION,
  AUTH_PERMISSION_RESOURCE,
  WILDCARD_PERMISSION,
} from '../../modules/auth/constants/auth-permission.constants';
import {
  upsertSystemRole,
  type UpsertSystemRoleInput,
} from '../../modules/auth/repositories/role.repository';
import { createPermissionCode } from '../../modules/auth/utils/permission-code.util';

export const systemRoleSeedMatrix: UpsertSystemRoleInput[] = [
  {
    code: AUTH_ROLE.CUSTOMER,
    name: 'Customer',
    permissions: [
      createPermissionCode(
        AUTH_PERMISSION_RESOURCE.CUSTOMER,
        AUTH_PERMISSION_ACTION.READ_SELF,
      ),
      createPermissionCode(
        AUTH_PERMISSION_RESOURCE.NOTIFICATIONS,
        AUTH_PERMISSION_ACTION.READ_SELF,
      ),
      createPermissionCode(
        AUTH_PERMISSION_RESOURCE.NOTIFICATIONS,
        AUTH_PERMISSION_ACTION.UPDATE_SELF,
      ),
    ],
  },
  {
    code: AUTH_ROLE.DELIVERY_AGENT,
    name: 'Delivery Agent',
    permissions: [
      createPermissionCode(
        AUTH_PERMISSION_RESOURCE.DELIVERY,
        AUTH_PERMISSION_ACTION.READ_SELF,
      ),
      createPermissionCode(
        AUTH_PERMISSION_RESOURCE.NOTIFICATIONS,
        AUTH_PERMISSION_ACTION.READ_SELF,
      ),
      createPermissionCode(
        AUTH_PERMISSION_RESOURCE.NOTIFICATIONS,
        AUTH_PERMISSION_ACTION.UPDATE_SELF,
      ),
    ],
  },
  {
    code: AUTH_ROLE.VENDOR_OWNER,
    name: 'Vendor Owner',
    permissions: [
      createPermissionCode(
        AUTH_PERMISSION_RESOURCE.VENDOR,
        AUTH_PERMISSION_ACTION.READ_STORE,
      ),
      createPermissionCode(AUTH_PERMISSION_RESOURCE.ORDERS, AUTH_PERMISSION_ACTION.READ),
      createPermissionCode(AUTH_PERMISSION_RESOURCE.ORDERS, AUTH_PERMISSION_ACTION.UPDATE),
      createPermissionCode(AUTH_PERMISSION_RESOURCE.INVENTORY, AUTH_PERMISSION_ACTION.READ),
      createPermissionCode(AUTH_PERMISSION_RESOURCE.INVENTORY, AUTH_PERMISSION_ACTION.UPDATE),
      createPermissionCode(AUTH_PERMISSION_RESOURCE.CATALOG, AUTH_PERMISSION_ACTION.READ),
      createPermissionCode(AUTH_PERMISSION_RESOURCE.CATALOG, AUTH_PERMISSION_ACTION.UPDATE),
      createPermissionCode(AUTH_PERMISSION_RESOURCE.STORE_PRODUCTS, AUTH_PERMISSION_ACTION.READ),
      createPermissionCode(AUTH_PERMISSION_RESOURCE.STORE_PRODUCTS, AUTH_PERMISSION_ACTION.UPDATE),
      createPermissionCode(AUTH_PERMISSION_RESOURCE.MEDIA, AUTH_PERMISSION_ACTION.READ),
      createPermissionCode(AUTH_PERMISSION_RESOURCE.MEDIA, AUTH_PERMISSION_ACTION.UPLOAD),
      createPermissionCode(AUTH_PERMISSION_RESOURCE.MEDIA, AUTH_PERMISSION_ACTION.DELETE),
      createPermissionCode(
        AUTH_PERMISSION_RESOURCE.NOTIFICATIONS,
        AUTH_PERMISSION_ACTION.READ_SELF,
      ),
      createPermissionCode(
        AUTH_PERMISSION_RESOURCE.NOTIFICATIONS,
        AUTH_PERMISSION_ACTION.UPDATE_SELF,
      ),
      createPermissionCode(AUTH_PERMISSION_RESOURCE.SETTINGS, AUTH_PERMISSION_ACTION.MANAGE),
    ],
  },
  {
    code: AUTH_ROLE.STORE_MANAGER,
    name: 'Store Manager',
    permissions: [
      createPermissionCode(
        AUTH_PERMISSION_RESOURCE.VENDOR,
        AUTH_PERMISSION_ACTION.READ_STORE,
      ),
      createPermissionCode(AUTH_PERMISSION_RESOURCE.ORDERS, AUTH_PERMISSION_ACTION.READ),
      createPermissionCode(AUTH_PERMISSION_RESOURCE.ORDERS, AUTH_PERMISSION_ACTION.UPDATE),
      createPermissionCode(AUTH_PERMISSION_RESOURCE.INVENTORY, AUTH_PERMISSION_ACTION.READ),
      createPermissionCode(AUTH_PERMISSION_RESOURCE.INVENTORY, AUTH_PERMISSION_ACTION.UPDATE),
      createPermissionCode(AUTH_PERMISSION_RESOURCE.CATALOG, AUTH_PERMISSION_ACTION.READ),
      createPermissionCode(AUTH_PERMISSION_RESOURCE.CATALOG, AUTH_PERMISSION_ACTION.UPDATE),
      createPermissionCode(AUTH_PERMISSION_RESOURCE.STORE_PRODUCTS, AUTH_PERMISSION_ACTION.READ),
      createPermissionCode(AUTH_PERMISSION_RESOURCE.STORE_PRODUCTS, AUTH_PERMISSION_ACTION.UPDATE),
      createPermissionCode(AUTH_PERMISSION_RESOURCE.MEDIA, AUTH_PERMISSION_ACTION.READ),
      createPermissionCode(AUTH_PERMISSION_RESOURCE.MEDIA, AUTH_PERMISSION_ACTION.UPLOAD),
      createPermissionCode(AUTH_PERMISSION_RESOURCE.MEDIA, AUTH_PERMISSION_ACTION.DELETE),
      createPermissionCode(
        AUTH_PERMISSION_RESOURCE.NOTIFICATIONS,
        AUTH_PERMISSION_ACTION.READ_SELF,
      ),
      createPermissionCode(
        AUTH_PERMISSION_RESOURCE.NOTIFICATIONS,
        AUTH_PERMISSION_ACTION.UPDATE_SELF,
      ),
    ],
  },
  {
    code: AUTH_ROLE.STORE_STAFF,
    name: 'Store Staff',
    permissions: [
      createPermissionCode(
        AUTH_PERMISSION_RESOURCE.VENDOR,
        AUTH_PERMISSION_ACTION.READ_STORE,
      ),
      createPermissionCode(AUTH_PERMISSION_RESOURCE.ORDERS, AUTH_PERMISSION_ACTION.READ),
      createPermissionCode(AUTH_PERMISSION_RESOURCE.INVENTORY, AUTH_PERMISSION_ACTION.READ),
      createPermissionCode(AUTH_PERMISSION_RESOURCE.CATALOG, AUTH_PERMISSION_ACTION.READ),
      createPermissionCode(AUTH_PERMISSION_RESOURCE.STORE_PRODUCTS, AUTH_PERMISSION_ACTION.READ),
      createPermissionCode(AUTH_PERMISSION_RESOURCE.STORE_PRODUCTS, AUTH_PERMISSION_ACTION.UPDATE),
      createPermissionCode(AUTH_PERMISSION_RESOURCE.MEDIA, AUTH_PERMISSION_ACTION.READ),
      createPermissionCode(AUTH_PERMISSION_RESOURCE.MEDIA, AUTH_PERMISSION_ACTION.UPLOAD),
      createPermissionCode(
        AUTH_PERMISSION_RESOURCE.NOTIFICATIONS,
        AUTH_PERMISSION_ACTION.READ_SELF,
      ),
      createPermissionCode(
        AUTH_PERMISSION_RESOURCE.NOTIFICATIONS,
        AUTH_PERMISSION_ACTION.UPDATE_SELF,
      ),
    ],
  },
  {
    code: AUTH_ROLE.SUPPORT_ADMIN,
    name: 'Support Admin',
    permissions: [
      createPermissionCode(AUTH_PERMISSION_RESOURCE.AUTH, AUTH_PERMISSION_ACTION.READ),
      createPermissionCode(AUTH_PERMISSION_RESOURCE.CUSTOMER, AUTH_PERMISSION_ACTION.READ),
      createPermissionCode(AUTH_PERMISSION_RESOURCE.USERS, AUTH_PERMISSION_ACTION.READ),
      createPermissionCode(AUTH_PERMISSION_RESOURCE.STORES, AUTH_PERMISSION_ACTION.READ),
      createPermissionCode(AUTH_PERMISSION_RESOURCE.LOCATIONS, AUTH_PERMISSION_ACTION.READ),
      createPermissionCode(AUTH_PERMISSION_RESOURCE.ORDERS, AUTH_PERMISSION_ACTION.READ),
      createPermissionCode(AUTH_PERMISSION_RESOURCE.DELIVERY, AUTH_PERMISSION_ACTION.READ),
      createPermissionCode(AUTH_PERMISSION_RESOURCE.CATALOG, AUTH_PERMISSION_ACTION.READ),
      createPermissionCode(AUTH_PERMISSION_RESOURCE.SUPPORT, AUTH_PERMISSION_ACTION.READ),
      createPermissionCode(AUTH_PERMISSION_RESOURCE.PUSH_NOTIFICATIONS, AUTH_PERMISSION_ACTION.READ),
      createPermissionCode(
        AUTH_PERMISSION_RESOURCE.REALTIME_CONTROL_TOWER,
        AUTH_PERMISSION_ACTION.READ,
      ),
      createPermissionCode(
        AUTH_PERMISSION_RESOURCE.NOTIFICATIONS,
        AUTH_PERMISSION_ACTION.READ_SELF,
      ),
      createPermissionCode(
        AUTH_PERMISSION_RESOURCE.NOTIFICATIONS,
        AUTH_PERMISSION_ACTION.UPDATE_SELF,
      ),
      createPermissionCode(AUTH_PERMISSION_RESOURCE.SETTINGS, AUTH_PERMISSION_ACTION.READ),
    ],
  },
  {
    code: AUTH_ROLE.OPERATIONS_ADMIN,
    name: 'Operations Admin',
    permissions: [
      createPermissionCode(AUTH_PERMISSION_RESOURCE.AUTH, AUTH_PERMISSION_ACTION.READ),
      createPermissionCode(AUTH_PERMISSION_RESOURCE.AUTH, AUTH_PERMISSION_ACTION.MANAGE),
      createPermissionCode(AUTH_PERMISSION_RESOURCE.CUSTOMER, AUTH_PERMISSION_ACTION.READ),
      createPermissionCode(AUTH_PERMISSION_RESOURCE.CUSTOMER, AUTH_PERMISSION_ACTION.UPDATE),
      createPermissionCode(
        AUTH_PERMISSION_RESOURCE.CUSTOMER,
        AUTH_PERMISSION_ACTION.UPDATE_STATUS,
      ),
      createPermissionCode(AUTH_PERMISSION_RESOURCE.USERS, AUTH_PERMISSION_ACTION.READ),
      createPermissionCode(AUTH_PERMISSION_RESOURCE.STORES, AUTH_PERMISSION_ACTION.READ),
      createPermissionCode(AUTH_PERMISSION_RESOURCE.LOCATIONS, AUTH_PERMISSION_ACTION.READ),
      createPermissionCode(AUTH_PERMISSION_RESOURCE.ORDERS, AUTH_PERMISSION_ACTION.READ),
      createPermissionCode(AUTH_PERMISSION_RESOURCE.ORDERS, AUTH_PERMISSION_ACTION.CANCEL),
      createPermissionCode(AUTH_PERMISSION_RESOURCE.ORDERS, AUTH_PERMISSION_ACTION.UPDATE),
      createPermissionCode(
        AUTH_PERMISSION_RESOURCE.ORDERS,
        AUTH_PERMISSION_ACTION.UPDATE_STATUS,
      ),
      createPermissionCode(AUTH_PERMISSION_RESOURCE.DELIVERY, AUTH_PERMISSION_ACTION.READ),
      createPermissionCode(AUTH_PERMISSION_RESOURCE.INVENTORY, AUTH_PERMISSION_ACTION.READ),
      createPermissionCode(AUTH_PERMISSION_RESOURCE.INVENTORY, AUTH_PERMISSION_ACTION.CREATE),
      createPermissionCode(AUTH_PERMISSION_RESOURCE.INVENTORY, AUTH_PERMISSION_ACTION.UPDATE),
      createPermissionCode(AUTH_PERMISSION_RESOURCE.INVENTORY, AUTH_PERMISSION_ACTION.DELETE),
      createPermissionCode(AUTH_PERMISSION_RESOURCE.INVENTORY, AUTH_PERMISSION_ACTION.ADJUST),
      createPermissionCode(AUTH_PERMISSION_RESOURCE.INVENTORY, AUTH_PERMISSION_ACTION.BULK_UPDATE),
      createPermissionCode(AUTH_PERMISSION_RESOURCE.CATALOG, AUTH_PERMISSION_ACTION.READ),
      createPermissionCode(AUTH_PERMISSION_RESOURCE.CATALOG, AUTH_PERMISSION_ACTION.CREATE),
      createPermissionCode(AUTH_PERMISSION_RESOURCE.CATALOG, AUTH_PERMISSION_ACTION.UPDATE),
      createPermissionCode(AUTH_PERMISSION_RESOURCE.CATALOG, AUTH_PERMISSION_ACTION.DELETE),
      createPermissionCode(AUTH_PERMISSION_RESOURCE.CATALOG, AUTH_PERMISSION_ACTION.APPROVE),
      createPermissionCode(AUTH_PERMISSION_RESOURCE.LOCATIONS, AUTH_PERMISSION_ACTION.CREATE),
      createPermissionCode(AUTH_PERMISSION_RESOURCE.LOCATIONS, AUTH_PERMISSION_ACTION.UPDATE),
      createPermissionCode(AUTH_PERMISSION_RESOURCE.LOCATIONS, AUTH_PERMISSION_ACTION.DELETE),
      createPermissionCode(AUTH_PERMISSION_RESOURCE.STORES, AUTH_PERMISSION_ACTION.CREATE),
      createPermissionCode(AUTH_PERMISSION_RESOURCE.STORES, AUTH_PERMISSION_ACTION.UPDATE),
      createPermissionCode(AUTH_PERMISSION_RESOURCE.STORES, AUTH_PERMISSION_ACTION.DELETE),
      createPermissionCode(AUTH_PERMISSION_RESOURCE.STORE_PRODUCTS, AUTH_PERMISSION_ACTION.READ),
      createPermissionCode(AUTH_PERMISSION_RESOURCE.STORE_PRODUCTS, AUTH_PERMISSION_ACTION.CREATE),
      createPermissionCode(AUTH_PERMISSION_RESOURCE.STORE_PRODUCTS, AUTH_PERMISSION_ACTION.UPDATE),
      createPermissionCode(AUTH_PERMISSION_RESOURCE.STORE_PRODUCTS, AUTH_PERMISSION_ACTION.DELETE),
      createPermissionCode(
        AUTH_PERMISSION_RESOURCE.STORE_PRODUCTS,
        AUTH_PERMISSION_ACTION.BULK_UPDATE,
      ),
      createPermissionCode(AUTH_PERMISSION_RESOURCE.FINANCE, AUTH_PERMISSION_ACTION.READ),
      createPermissionCode(AUTH_PERMISSION_RESOURCE.MEDIA, AUTH_PERMISSION_ACTION.READ),
      createPermissionCode(AUTH_PERMISSION_RESOURCE.MEDIA, AUTH_PERMISSION_ACTION.UPLOAD),
      createPermissionCode(AUTH_PERMISSION_RESOURCE.MEDIA, AUTH_PERMISSION_ACTION.UPDATE),
      createPermissionCode(AUTH_PERMISSION_RESOURCE.MEDIA, AUTH_PERMISSION_ACTION.DELETE),
      createPermissionCode(AUTH_PERMISSION_RESOURCE.PUSH_NOTIFICATIONS, AUTH_PERMISSION_ACTION.READ),
      createPermissionCode(
        AUTH_PERMISSION_RESOURCE.REALTIME_CONTROL_TOWER,
        AUTH_PERMISSION_ACTION.READ,
      ),
      createPermissionCode(
        AUTH_PERMISSION_RESOURCE.NOTIFICATIONS,
        AUTH_PERMISSION_ACTION.READ_SELF,
      ),
      createPermissionCode(
        AUTH_PERMISSION_RESOURCE.NOTIFICATIONS,
        AUTH_PERMISSION_ACTION.UPDATE_SELF,
      ),
      createPermissionCode(AUTH_PERMISSION_RESOURCE.SETTINGS, AUTH_PERMISSION_ACTION.MANAGE),
    ],
  },
  {
    code: AUTH_ROLE.SUPER_ADMIN,
    name: 'Super Admin',
    permissions: [WILDCARD_PERMISSION],
  },
];

export const seedRoles = async (dryRun: boolean): Promise<void> => {
  if (dryRun) {
    console.log(
      `Dry run: roles seed skipped for ${systemRoleSeedMatrix.map((role) => role.code).join(', ')}`,
    );
    return;
  }

  for (const role of systemRoleSeedMatrix) {
    await upsertSystemRole({
      ...role,
      description: null,
      isSystemRole: true,
      isEditable: false,
    });
  }

  console.log('System roles seeded');
};
